<?php

$namesByNation = [
    "Argentina" => [
        ["firstname" => "Matías", "lastname" => "González"],
        ["firstname" => "Valentina", "lastname" => "Pérez"],
        ["firstname" => "Nicolás", "lastname" => "Fernández"],
        ["firstname" => "Camila", "lastname" => "Rodríguez"],
        ["firstname" => "Juan", "lastname" => "Martínez"],
        ["firstname" => "Santiago", "lastname" => "Romero"],
        ["firstname" => "Sofía", "lastname" => "Vega"],
        ["firstname" => "Facundo", "lastname" => "Morales"],
        ["firstname" => "Agustina", "lastname" => "Gutiérrez"],
        ["firstname" => "Tomás", "lastname" => "Díaz"],
    ],
    "France" => [
        ["firstname" => "Lucas", "lastname" => "Bernard"],
        ["firstname" => "Chloé", "lastname" => "Dubois"],
        ["firstname" => "Gabriel", "lastname" => "Moreau"],
        ["firstname" => "Emma", "lastname" => "Fournier"],
        ["firstname" => "Louis", "lastname" => "Girard"],
        ["firstname" => "Léa", "lastname" => "Lambert"],
        ["firstname" => "Hugo", "lastname" => "Martineau"],
        ["firstname" => "Alice", "lastname" => "Lemoine"],
        ["firstname" => "Arthur", "lastname" => "Rousseau"],
        ["firstname" => "Manon", "lastname" => "Chevalier"],
    ],
    "Brazil" => [
        ["firstname" => "Gabriel", "lastname" => "Silva"],
        ["firstname" => "Julia", "lastname" => "Oliveira"],
        ["firstname" => "Pedro", "lastname" => "Souza"],
        ["firstname" => "Ana", "lastname" => "Ferreira"],
        ["firstname" => "Rafael", "lastname" => "Almeida"],
        ["firstname" => "Isabela", "lastname" => "Castro"],
        ["firstname" => "Lucas", "lastname" => "Costa"],
        ["firstname" => "Mariana", "lastname" => "Ribeiro"],
        ["firstname" => "Felipe", "lastname" => "Gomes"],
        ["firstname" => "Carolina", "lastname" => "Santos"],
    ],
    "England" => [
        ["firstname" => "Oliver", "lastname" => "Taylor"],
        ["firstname" => "Amelia", "lastname" => "Brown"],
        ["firstname" => "Jack", "lastname" => "Wilson"],
        ["firstname" => "Isla", "lastname" => "Evans"],
        ["firstname" => "Henry", "lastname" => "Thomas"],
        ["firstname" => "Emily", "lastname" => "Johnson"],
        ["firstname" => "George", "lastname" => "Hall"],
        ["firstname" => "Mia", "lastname" => "Adams"],
        ["firstname" => "Freddie", "lastname" => "Walker"],
        ["firstname" => "Sophie", "lastname" => "Green"],
    ],
    "Belgium" => [
        ["firstname" => "Noah", "lastname" => "Peeters"],
        ["firstname" => "Liam", "lastname" => "Dupont"],
        ["firstname" => "Emma", "lastname" => "De Smet"],
        ["firstname" => "Olivia", "lastname" => "Vermeulen"],
        ["firstname" => "Lucas", "lastname" => "Jacobs"],
        ["firstname" => "Mila", "lastname" => "Willems"],
        ["firstname" => "Nathan", "lastname" => "Maes"],
        ["firstname" => "Charlotte", "lastname" => "De Wit"],
        ["firstname" => "Eli", "lastname" => "Janssen"],
        ["firstname" => "Ella", "lastname" => "Claes"],
    ],
    "Portugal" => [
        ["firstname" => "Francisco", "lastname" => "Alves"],
        ["firstname" => "Beatriz", "lastname" => "Pereira"],
        ["firstname" => "Tiago", "lastname" => "Monteiro"],
        ["firstname" => "Inês", "lastname" => "Carvalho"],
        ["firstname" => "João", "lastname" => "Martins"],
        ["firstname" => "Leonor", "lastname" => "Sousa"],
        ["firstname" => "Miguel", "lastname" => "Rodrigues"],
        ["firstname" => "Sofia", "lastname" => "Fernandes"],
        ["firstname" => "Diogo", "lastname" => "Costa"],
        ["firstname" => "Ana", "lastname" => "Gonçalves"],
    ],
    "Netherlands" => [
        ["firstname" => "Daan", "lastname" => "de Jong"],
        ["firstname" => "Lotte", "lastname" => "Jansen"],
        ["firstname" => "Ruben", "lastname" => "Bakker"],
        ["firstname" => "Sanne", "lastname" => "Visser"],
        ["firstname" => "Mees", "lastname" => "Smit"],
        ["firstname" => "Fleur", "lastname" => "de Vries"],
        ["firstname" => "Milan", "lastname" => "Hofman"],
        ["firstname" => "Tess", "lastname" => "Kramer"],
        ["firstname" => "Jasper", "lastname" => "de Boer"],
        ["firstname" => "Evi", "lastname" => "Peters"],
    ],
    "Spain" => [
        ["firstname" => "Alejandro", "lastname" => "Garcia"],
        ["firstname" => "Lucía", "lastname" => "Fernandez"],
        ["firstname" => "Carlos", "lastname" => "Lopez"],
        ["firstname" => "Maria", "lastname" => "Martinez"],
        ["firstname" => "Hugo", "lastname" => "Sanchez"],
        ["firstname" => "Sofia", "lastname" => "Gonzalez"],
        ["firstname" => "Daniel", "lastname" => "Perez"],
        ["firstname" => "Paula", "lastname" => "Diaz"],
        ["firstname" => "Javier", "lastname" => "Moreno"],
        ["firstname" => "Claudia", "lastname" => "Ruiz"],
    ],
    "Italy" => [
        ["firstname" => "Lorenzo", "lastname" => "Russo"],
        ["firstname" => "Giulia", "lastname" => "Ferrari"],
        ["firstname" => "Andrea", "lastname" => "Romano"],
        ["firstname" => "Martina", "lastname" => "Galli"],
        ["firstname" => "Marco", "lastname" => "Ricci"],
        ["firstname" => "Chiara", "lastname" => "Rossi"],
        ["firstname" => "Davide", "lastname" => "Greco"],
        ["firstname" => "Elena", "lastname" => "Conti"],
        ["firstname" => "Matteo", "lastname" => "Lombardi"],
        ["firstname" => "Aurora", "lastname" => "Barbieri"],
    ],
    "Croatia" => [
        ["firstname" => "Marko", "lastname" => "Horvat"],
        ["firstname" => "Ivana", "lastname" => "Novak"],
        ["firstname" => "Ivan", "lastname" => "Kovac"],
        ["firstname" => "Ana", "lastname" => "Maric"],
        ["firstname" => "Luka", "lastname" => "Jelic"],
        ["firstname" => "Maja", "lastname" => "Petrovic"],
        ["firstname" => "Filip", "lastname" => "Tomic"],
        ["firstname" => "Lucija", "lastname" => "Matic"],
        ["firstname" => "Nikola", "lastname" => "Boric"],
        ["firstname" => "Petra", "lastname" => "Radic"],
    ],
    "Germany" => [
        ["firstname" => "Maximilian", "lastname" => "Müller"],
        ["firstname" => "Sophia", "lastname" => "Schmidt"],
        ["firstname" => "Felix", "lastname" => "Schneider"],
        ["firstname" => "Hannah", "lastname" => "Fischer"],
        ["firstname" => "Lukas", "lastname" => "Weber"],
        ["firstname" => "Emma", "lastname" => "Becker"],
        ["firstname" => "Paul", "lastname" => "Hoffmann"],
        ["firstname" => "Lina", "lastname" => "Krause"],
        ["firstname" => "Jonas", "lastname" => "Wagner"],
        ["firstname" => "Marie", "lastname" => "Bauer"],
    ],
    "Morocco" => [
        ["firstname" => "Youssef", "lastname" => "El Amrani"],
        ["firstname" => "Fatima", "lastname" => "Bouazza"],
        ["firstname" => "Rachid", "lastname" => "El Idrissi"],
        ["firstname" => "Amina", "lastname" => "Bennani"],
        ["firstname" => "Karim", "lastname" => "Ouazzani"],
        ["firstname" => "Leila", "lastname" => "Tazi"],
        ["firstname" => "Omar", "lastname" => "Bouzid"],
        ["firstname" => "Nadia", "lastname" => "El Fakir"],
        ["firstname" => "Mohamed", "lastname" => "Belhaj"],
        ["firstname" => "Khadija", "lastname" => "Cherkaoui"],
    ],
    "Mexico" => [
        ["firstname" => "Juan", "lastname" => "Hernández"],
        ["firstname" => "Maria", "lastname" => "García"],
        ["firstname" => "Carlos", "lastname" => "Martínez"],
        ["firstname" => "Guadalupe", "lastname" => "López"],
        ["firstname" => "José", "lastname" => "González"],
        ["firstname" => "Ana", "lastname" => "Rodríguez"],
        ["firstname" => "Miguel", "lastname" => "Pérez"],
        ["firstname" => "Sofía", "lastname" => "Sánchez"],
        ["firstname" => "Diego", "lastname" => "Ramírez"],
        ["firstname" => "Daniela", "lastname" => "Torres"],
    ],
    "Uruguay" => [
        ["firstname" => "Martín", "lastname" => "Rodríguez"],
        ["firstname" => "Florencia", "lastname" => "Fernández"],
        ["firstname" => "Matías", "lastname" => "Pérez"],
        ["firstname" => "Camila", "lastname" => "García"],
        ["firstname" => "Juan", "lastname" => "González"],
        ["firstname" => "Sofía", "lastname" => "Martínez"],
        ["firstname" => "Facundo", "lastname" => "Lopez"],
        ["firstname" => "Agustina", "lastname" => "Sánchez"],
        ["firstname" => "Lucas", "lastname" => "Ramírez"],
        ["firstname" => "Valentina", "lastname" => "Alonso"],
    ],
    "Switzerland" => [
        ["firstname" => "Liam", "lastname" => "Meyer"],
        ["firstname" => "Emma", "lastname" => "Fischer"],
        ["firstname" => "Noah", "lastname" => "Weber"],
        ["firstname" => "Mia", "lastname" => "Müller"],
        ["firstname" => "Lea", "lastname" => "Zimmermann"],
        ["firstname" => "Luca", "lastname" => "Hofmann"],
        ["firstname" => "Elena", "lastname" => "Bauer"],
        ["firstname" => "Jonas", "lastname" => "Schmid"],
        ["firstname" => "Nina", "lastname" => "Berger"],
        ["firstname" => "Tim", "lastname" => "Keller"],
    ],
    "Colombia" => [
        ["firstname" => "Santiago", "lastname" => "Gómez"],
        ["firstname" => "Valeria", "lastname" => "Rodríguez"],
        ["firstname" => "Sebastián", "lastname" => "Martínez"],
        ["firstname" => "Camila", "lastname" => "López"],
        ["firstname" => "Juan", "lastname" => "Hernández"],
        ["firstname" => "Mariana", "lastname" => "Pérez"],
        ["firstname" => "Andrés", "lastname" => "Torres"],
        ["firstname" => "Isabella", "lastname" => "Ramírez"],
        ["firstname" => "Nicolás", "lastname" => "García"],
        ["firstname" => "Laura", "lastname" => "Castro"],
    ],
    "Senegal" => [
        ["firstname" => "Mamadou", "lastname" => "Diop"],
        ["firstname" => "Awa", "lastname" => "Ndiaye"],
        ["firstname" => "Ibrahima", "lastname" => "Faye"],
        ["firstname" => "Fatou", "lastname" => "Ba"],
        ["firstname" => "Cheikh", "lastname" => "Sy"],
        ["firstname" => "Mariama", "lastname" => "Fall"],
        ["firstname" => "Ousmane", "lastname" => "Thiam"],
        ["firstname" => "Astou", "lastname" => "Gaye"],
        ["firstname" => "Amadou", "lastname" => "Sow"],
        ["firstname" => "Khady", "lastname" => "Camara"],
    ],
    "USA" => [
        ["firstname" => "James", "lastname" => "Johnson"],
        ["firstname" => "Emma", "lastname" => "Brown"],
        ["firstname" => "Michael", "lastname" => "Williams"],
        ["firstname" => "Olivia", "lastname" => "Jones"],
        ["firstname" => "William", "lastname" => "Garcia"],
        ["firstname" => "Sophia", "lastname" => "Miller"],
        ["firstname" => "Ethan", "lastname" => "Davis"],
        ["firstname" => "Isabella", "lastname" => "Martinez"],
        ["firstname" => "Daniel", "lastname" => "Hernandez"],
        ["firstname" => "Ava", "lastname" => "Lopez"],
    ],
    "Japan" => [
        ["firstname" => "Hiroshi", "lastname" => "Tanaka"],
        ["firstname" => "Yumi", "lastname" => "Nakamura"],
        ["firstname" => "Kenta", "lastname" => "Yamamoto"],
        ["firstname" => "Aiko", "lastname" => "Kobayashi"],
        ["firstname" => "Satoshi", "lastname" => "Matsumoto"],
        ["firstname" => "Rina", "lastname" => "Takahashi"],
        ["firstname" => "Takeshi", "lastname" => "Sasaki"],
        ["firstname" => "Haruka", "lastname" => "Fujimoto"],
        ["firstname" => "Ryota", "lastname" => "Okada"],
        ["firstname" => "Kana", "lastname" => "Shimizu"],
    ],
    "Denmark" => [
        ["firstname" => "Lucas", "lastname" => "Hansen"],
        ["firstname" => "Freja", "lastname" => "Nielsen"],
        ["firstname" => "Oliver", "lastname" => "Jensen"],
        ["firstname" => "Emma", "lastname" => "Pedersen"],
        ["firstname" => "Oscar", "lastname" => "Andersen"],
        ["firstname" => "Sofia", "lastname" => "Christensen"],
        ["firstname" => "Noah", "lastname" => "Larsen"],
        ["firstname" => "Maja", "lastname" => "Rasmussen"],
        ["firstname" => "Victor", "lastname" => "Sorensen"],
        ["firstname" => "Clara", "lastname" => "Mikkelsen"],
    ],
    "Australia" => [
        ["firstname" => "Liam", "lastname" => "Smith"],
        ["firstname" => "Olivia", "lastname" => "Brown"],
        ["firstname" => "Ethan", "lastname" => "Wilson"],
        ["firstname" => "Charlotte", "lastname" => "Taylor"],
        ["firstname" => "Jack", "lastname" => "Johnson"],
        ["firstname" => "Ava", "lastname" => "Williams"],
        ["firstname" => "Harry", "lastname" => "Jones"],
        ["firstname" => "Mia", "lastname" => "Miller"],
        ["firstname" => "Benjamin", "lastname" => "Davis"],
        ["firstname" => "Emily", "lastname" => "Anderson"],
    ],
    "Serbia" => [
        ["firstname" => "Nikola", "lastname" => "Markovic"],
        ["firstname" => "Jovana", "lastname" => "Petrovic"],
        ["firstname" => "Milos", "lastname" => "Jovanovic"],
        ["firstname" => "Ana", "lastname" => "Nikolic"],
        ["firstname" => "Luka", "lastname" => "Stevanovic"],
        ["firstname" => "Ivana", "lastname" => "Milosevic"],
        ["firstname" => "Filip", "lastname" => "Djurdjevic"],
        ["firstname" => "Milica", "lastname" => "Kostic"],
        ["firstname" => "Marko", "lastname" => "Stojanovic"],
        ["firstname" => "Jelena", "lastname" => "Pavlovic"],
    ],
    "Poland" => [
        ["firstname" => "Jakub", "lastname" => "Nowak"],
        ["firstname" => "Anna", "lastname" => "Kowalska"],
        ["firstname" => "Piotr", "lastname" => "Wiśniewski"],
        ["firstname" => "Katarzyna", "lastname" => "Wójcik"],
        ["firstname" => "Marek", "lastname" => "Kaminski"],
        ["firstname" => "Zofia", "lastname" => "Lewandowska"],
        ["firstname" => "Tomasz", "lastname" => "Dąbrowski"],
        ["firstname" => "Magdalena", "lastname" => "Zielinska"],
        ["firstname" => "Wojciech", "lastname" => "Szymański"],
        ["firstname" => "Agnieszka", "lastname" => "Pawlak"],
    ],
    "Iran" => [
        ["firstname" => "Ali", "lastname" => "Hosseini"],
        ["firstname" => "Fatemeh", "lastname" => "Mohammadi"],
        ["firstname" => "Reza", "lastname" => "Karimi"],
        ["firstname" => "Zahra", "lastname" => "Ahmadi"],
        ["firstname" => "Mohammad", "lastname" => "Ebrahimi"],
        ["firstname" => "Sara", "lastname" => "Rasouli"],
        ["firstname" => "Hossein", "lastname" => "Sadeghi"],
        ["firstname" => "Maryam", "lastname" => "Kazemi"],
        ["firstname" => "Mehdi", "lastname" => "Gholami"],
        ["firstname" => "Amin", "lastname" => "Najafi"],
    ],
    "Korea Republic" => [
        ["firstname" => "Jae-ho", "lastname" => "Kim"],
        ["firstname" => "Min-seo", "lastname" => "Park"],
        ["firstname" => "Hyun-woo", "lastname" => "Lee"],
        ["firstname" => "Ji-hyun", "lastname" => "Choi"],
        ["firstname" => "Dong-hyun", "lastname" => "Jeong"],
        ["firstname" => "Seo-yeon", "lastname" => "Yoon"],
        ["firstname" => "Jin-ho", "lastname" => "Jang"],
        ["firstname" => "Ha-eun", "lastname" => "Kang"],
        ["firstname" => "Sung-min", "lastname" => "Oh"],
        ["firstname" => "Hye-jin", "lastname" => "Moon"],
    ],
    "Peru" => [
        ["firstname" => "Juan", "lastname" => "Castro"],
        ["firstname" => "Rosa", "lastname" => "Sánchez"],
        ["firstname" => "Carlos", "lastname" => "Flores"],
        ["firstname" => "María", "lastname" => "Guzmán"],
        ["firstname" => "José", "lastname" => "Ortega"],
        ["firstname" => "Ana", "lastname" => "Vargas"],
        ["firstname" => "Luis", "lastname" => "Mendoza"],
        ["firstname" => "Carmen", "lastname" => "Rojas"],
        ["firstname" => "Miguel", "lastname" => "Chávez"],
        ["firstname" => "Elena", "lastname" => "Salazar"],
    ],
    "Sweden" => [
        ["firstname" => "Erik", "lastname" => "Johansson"],
        ["firstname" => "Maja", "lastname" => "Andersson"],
        ["firstname" => "William", "lastname" => "Karlsson"],
        ["firstname" => "Alice", "lastname" => "Nilsson"],
        ["firstname" => "Lucas", "lastname" => "Svensson"],
        ["firstname" => "Elin", "lastname" => "Olsson"],
        ["firstname" => "Oscar", "lastname" => "Lindberg"],
        ["firstname" => "Ebba", "lastname" => "Persson"],
        ["firstname" => "Axel", "lastname" => "Pettersson"],
        ["firstname" => "Nora", "lastname" => "Berg"],
    ],
    "Ukraine" => [
        ["firstname" => "Dmytro", "lastname" => "Shevchenko"],
        ["firstname" => "Olena", "lastname" => "Bondarenko"],
        ["firstname" => "Oleksandr", "lastname" => "Tkachenko"],
        ["firstname" => "Yulia", "lastname" => "Koval"],
        ["firstname" => "Andriy", "lastname" => "Kravchenko"],
        ["firstname" => "Iryna", "lastname" => "Melnyk"],
        ["firstname" => "Viktor", "lastname" => "Klymenko"],
        ["firstname" => "Tetiana", "lastname" => "Hryhorenko"],
        ["firstname" => "Roman", "lastname" => "Horbach"],
        ["firstname" => "Kateryna", "lastname" => "Mazurenko"],
    ],
    "Chile" => [
        ["firstname" => "Francisco", "lastname" => "Muñoz"],
        ["firstname" => "Antonia", "lastname" => "Rojas"],
        ["firstname" => "Matías", "lastname" => "Gutiérrez"],
        ["firstname" => "Valentina", "lastname" => "Paredes"],
        ["firstname" => "Sebastián", "lastname" => "Vergara"],
        ["firstname" => "Camila", "lastname" => "Reyes"],
        ["firstname" => "Cristóbal", "lastname" => "Navarro"],
        ["firstname" => "Fernanda", "lastname" => "Vargas"],
        ["firstname" => "Diego", "lastname" => "Cortez"],
        ["firstname" => "Isabella", "lastname" => "Morales"],
    ],
    "Egypt" => [
        ["firstname" => "Ahmed", "lastname" => "Ali"],
        ["firstname" => "Fatma", "lastname" => "Hassan"],
        ["firstname" => "Mohamed", "lastname" => "Youssef"],
        ["firstname" => "Nour", "lastname" => "Mahmoud"],
        ["firstname" => "Omar", "lastname" => "Ismail"],
        ["firstname" => "Aya", "lastname" => "Sayed"],
        ["firstname" => "Khaled", "lastname" => "Farouk"],
        ["firstname" => "Mona", "lastname" => "Shahin"],
        ["firstname" => "Hussein", "lastname" => "Sobhy"],
        ["firstname" => "Salma", "lastname" => "Abdelrahman"],
    ],
    "Nigeria" => [
        ["firstname" => "Chinedu", "lastname" => "Okafor"],
        ["firstname" => "Amarachi", "lastname" => "Nwosu"],
        ["firstname" => "Tolu", "lastname" => "Adesina"],
        ["firstname" => "Emeka", "lastname" => "Iheanacho"],
        ["firstname" => "Funmi", "lastname" => "Ogunleye"],
        ["firstname" => "Kelechi", "lastname" => "Eze"],
        ["firstname" => "Ngozi", "lastname" => "Onyekuru"],
        ["firstname" => "Segun", "lastname" => "Bello"],
        ["firstname" => "Ifeoma", "lastname" => "Uche"],
        ["firstname" => "Tunde", "lastname" => "Oluwafemi"],
    ],
    "Tunisia" => [
        ["firstname" => "Mohamed", "lastname" => "Ben Ali"],
        ["firstname" => "Aymen", "lastname" => "Abdelkader"],
        ["firstname" => "Houssem", "lastname" => "Jemaa"],
        ["firstname" => "Fethi", "lastname" => "Belhaj"],
        ["firstname" => "Riadh", "lastname" => "Chikhaoui"],
        ["firstname" => "Yassine", "lastname" => "Khelil"],
        ["firstname" => "Amine", "lastname" => "Haddadi"],
        ["firstname" => "Anis", "lastname" => "Bouazizi"],
        ["firstname" => "Chamseddine", "lastname" => "Harbaoui"],
        ["firstname" => "Sabri", "lastname" => "Gharbi"],
    ],
    "Saudi Arabia" => [
        ["firstname" => "Fahad", "lastname" => "Al-Mutairi"],
        ["firstname" => "Salman", "lastname" => "Al-Harbi"],
        ["firstname" => "Nasser", "lastname" => "Al-Qahtani"],
        ["firstname" => "Majed", "lastname" => "Al-Otaibi"],
        ["firstname" => "Yasir", "lastname" => "Al-Dosari"],
        ["firstname" => "Abdulrahman", "lastname" => "Al-Ghamdi"],
        ["firstname" => "Omar", "lastname" => "Al-Suhaimi"],
        ["firstname" => "Bander", "lastname" => "Al-Shammari"],
        ["firstname" => "Ibrahim", "lastname" => "Al-Rashidi"],
        ["firstname" => "Khaled", "lastname" => "Al-Omari"],
    ],
    "Ecuador" => [
        ["firstname" => "Diego", "lastname" => "Castillo"],
        ["firstname" => "Carlos", "lastname" => "Aguirre"],
        ["firstname" => "Javier", "lastname" => "Molina"],
        ["firstname" => "Luis", "lastname" => "Espinoza"],
        ["firstname" => "Daniel", "lastname" => "Valencia"],
        ["firstname" => "Andrés", "lastname" => "Ayala"],
        ["firstname" => "Sofia", "lastname" => "Guerrero"],
        ["firstname" => "María", "lastname" => "Torres"],
        ["firstname" => "Juan", "lastname" => "Reyes"],
        ["firstname" => "Esteban", "lastname" => "Cabrera"],
    ],
    "Czech Republic" => [
        ["firstname" => "Petr", "lastname" => "Novák"],
        ["firstname" => "Jan", "lastname" => "Svoboda"],
        ["firstname" => "Lukáš", "lastname" => "Černý"],
        ["firstname" => "Tereza", "lastname" => "Procházková"],
        ["firstname" => "Kateřina", "lastname" => "Horáková"],
        ["firstname" => "Ondřej", "lastname" => "Krejčí"],
        ["firstname" => "Vojtěch", "lastname" => "Král"],
        ["firstname" => "Eliška", "lastname" => "Jelínková"],
        ["firstname" => "Tomáš", "lastname" => "Dvořák"],
        ["firstname" => "Adéla", "lastname" => "Zemanová"],
    ],
    "Austria" => [
        ["firstname" => "Lukas", "lastname" => "Bauer"],
        ["firstname" => "Florian", "lastname" => "Huber"],
        ["firstname" => "David", "lastname" => "Müller"],
        ["firstname" => "Anna", "lastname" => "Schmid"],
        ["firstname" => "Sophia", "lastname" => "Mayer"],
        ["firstname" => "Maximilian", "lastname" => "Weber"],
        ["firstname" => "Johanna", "lastname" => "Fischer"],
        ["firstname" => "Matthias", "lastname" => "Wagner"],
        ["firstname" => "Katharina", "lastname" => "Berger"],
        ["firstname" => "Stefan", "lastname" => "Gruber"],
    ],
];
define("DEFAULT_NAME_BY_NATIONALITY", $namesByNation);

const DEFAULT_FOOTBALL_TEAM = [
    [
        'uuid' => '1b6f4567-89a1-4c12-b2d3-7456123a7890',
        'slug' => 'phoenix-titans',
        'name' => 'Phoenix Titans',
    ],
    [
        'uuid' => '2c7e5678-90b2-5d23-c3e4-8567234b8901',
        'slug' => 'atlas-warriors',
        'name' => 'Atlas Warriors',
    ],
    [
        'uuid' => '3d8f6789-01c3-6e34-d4f5-9678345c9012',
        'slug' => 'crimson-falcons',
        'name' => 'Crimson Falcons',
    ],
    [
        'uuid' => '4e9g7890-12d4-7f45-e5g6-0789456d0123',
        'slug' => 'iron-wolves',
        'name' => 'Iron Wolves',
    ],
    [
        'uuid' => '5fah8901-23e5-8g56-f6h7-1890567e1234',
        'slug' => 'olympus-storm',
        'name' => 'Olympus Storm',
    ],
    [
        'uuid' => '6gbi9012-34f6-9h67-g7i8-2901678f2345',
        'slug' => 'eternal-dragons',
        'name' => 'Eternal Dragons',
    ],
    [
        'uuid' => '7hcj0123-45g7-0i78-h8j9-301278901345',
        'slug' => 'shadow-panthers',
        'name' => 'Shadow Panthers',
    ],
    [
        'uuid' => '8idk1234-56h8-1j89-i9k0-412389012456',
        'slug' => 'thundering-rhinos',
        'name' => 'Thundering Rhinos',
    ],
    [
        'uuid' => '9jel2345-67i9-2k90-j0l1-523490123567',
        'slug' => 'golden-stallions',
        'name' => 'Golden Stallions',
    ],
    [
        'uuid' => 'akfm3456-78j0-3l01-k1m2-634501234678',
        'slug' => 'silver-hawks',
        'name' => 'Silver Hawks',
    ],
    [
        'uuid' => 'bgln4567-89k1-4m12-l2n3-745612345789',
        'slug' => 'frost-giants',
        'name' => 'Frost Giants',
    ],
    [
        'uuid' => 'chmo5678-90l2-5n23-m3o4-856723456890',
        'slug' => 'midnight-torches',
        'name' => 'Midnight Torches',
    ],
    [
        'uuid' => 'dimp6789-01m3-6o34-n4p5-967834567901',
        'slug' => 'emerald-guardians',
        'name' => 'Emerald Guardians',
    ],
    [
        'uuid' => 'ejnq7890-12n4-7p45-o5q6-078945678012',
        'slug' => 'scarlet-blades',
        'name' => 'Scarlet Blades',
    ],
    [
        'uuid' => 'fkpr8901-23o5-8q56-p6r7-189056789123',
        'slug' => 'azure-knights',
        'name' => 'Azure Knights',
    ],
    [
        'uuid' => 'glqs9012-34p6-9r67-q7s8-290167890234',
        'slug' => 'ivory-sharks',
        'name' => 'Ivory Sharks',
    ],
    [
        'uuid' => 'hmrt0123-45q7-0s78-r8t9-301278901345',
        'slug' => 'blazing-comets',
        'name' => 'Blazing Comets',
    ],
    [
        'uuid' => 'inuv1234-56r8-1t89-s9u0-412389012456',
        'slug' => 'volcanic-eagles',
        'name' => 'Volcanic Eagles',
    ],
    [
        'uuid' => 'jowv2345-67s9-2u90-t0v1-523490123567',
        'slug' => 'steel-spartans',
        'name' => 'Steel Spartans',
    ],
    [
        'uuid' => 'kpxw3456-78t0-3v01-u1w2-634501234678',
        'slug' => 'radiant-monarchs',
        'name' => 'Radiant Monarchs',
    ],
    [
        'uuid' => 'lqwr4567-89z1-4w23-l2t4-745612345890',
        'slug' => 'celestial-tigers',
        'name' => 'Celestial Tigers',
    ],
    [
        'uuid' => 'mrst5678-90v2-5r34-n3s5-856723456901',
        'slug' => 'midnight-hawks',
        'name' => 'Midnight Hawks',
    ],
    [
        'uuid' => 'nuvq6789-01w3-6s45-m4t6-967834567902',
        'slug' => 'radiant-dragons',
        'name' => 'Radiant Dragons',
    ],
    [
        'uuid' => 'opfr7890-12x4-7z56-n5u7-078945678013',
        'slug' => 'thunder-spire',
        'name' => 'Thunder Spire',
    ],
    [
        'uuid' => 'pqgs8901-23z5-8w67-v6t8-189056789124',
        'slug' => 'gale-warriors',
        'name' => 'Gale Warriors',
    ],
    [
        'uuid' => 'qrtu9012-34u6-9x78-p7w9-290167890235',
        'slug' => 'storm-guardians',
        'name' => 'Storm Guardians',
    ],
    [
        'uuid' => 'rsuv2345-67w8-3y90-v7z1-523490123578',
        'slug' => 'lunar-knights',
        'name' => 'Lunar Knights',
    ],
    [
        'uuid' => 'stuw3456-78x9-4z01-w8y2-634501234679',
        'slug' => 'solar-ascendants',
        'name' => 'Solar Ascendants',
    ],
    [
        'uuid' => 'txyv4567-89y0-5w12-x9z3-745612345790',
        'slug' => 'oceanic-phantoms',
        'name' => 'Oceanic Phantoms',
    ],
    [
        'uuid' => 'uxyz5678-90z1-6y23-v0w4-856723456902',
        'slug' => 'crystal-vipers',
        'name' => 'Crystal Vipers',
    ],
    [
        'uuid' => 'vyza6789-01x2-7z34-w1y5-967834567903',
        'slug' => 'diamond-fury',
        'name' => 'Diamond Fury',
    ],
    [
        'uuid' => 'wzab7890-12y3-8z56-v2x7-078945678014',
        'slug' => 'wildfire-predators',
        'name' => 'Wildfire Predators',
    ],
    [
        'uuid' => 'xabc8901-23z4-9x67-y3z8-189056789125',
        'slug' => 'storm-wolves',
        'name' => 'Storm Wolves',
    ],
    [
        'uuid' => 'ydef9012-34z5-0w78-x6y9-290167890236',
        'slug' => 'frost-wardens',
        'name' => 'Frost Wardens',
    ],
    [
        'uuid' => 'zghj0123-45w6-2z89-v7y0-301278901346',
        'slug' => 'blizzard-sentinels',
        'name' => 'Blizzard Sentinels',
    ]
];

$formations = [
    [
        "slug" => "433",
        "name" => "4-3-3",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["LCM", "CM", "RCM"],
            "forwards" => ["LW", "CF", "RW"]
        ]
    ],
    [
        "slug" => "442",
        "name" => "4-4-2",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["LM", "CM", "CM", "RM"],
            "forwards" => ["ST", "ST"]
        ]
    ],
    [
        "slug" => "352",
        "name" => "3-5-2",
        "player_positions" => [
            "defenders" => ["CB", "CB", "CB"],
            "midfielders" => ["LM", "LCM", "CM", "RCM", "RM"],
            "forwards" => ["ST", "ST"]
        ]
    ],
    [
        "slug" => "4231",
        "name" => "4-2-3-1",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["CDM", "CDM", "CAM", "LW", "RW"],
            "forwards" => ["ST"]
        ]
    ],
    [
        "slug" => "4141",
        "name" => "4-1-4-1",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["CDM", "LM", "CM", "CM", "RM"],
            "forwards" => ["ST"]
        ]
    ],
    [
        "slug" => "541",
        "name" => "5-4-1",
        "player_positions" => [
            "defenders" => ["LWB", "CB", "CB", "CB", "RWB"],
            "midfielders" => ["LM", "CM", "CM", "RM"],
            "forwards" => ["ST"]
        ]
    ],
    [
        "slug" => "4312",
        "name" => "4-3-1-2",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["LCM", "CM", "RCM", "CAM"],
            "forwards" => ["ST", "ST"]
        ]
    ],
    [
        "slug" => "343",
        "name" => "3-4-3",
        "player_positions" => [
            "defenders" => ["CB", "CB", "CB"],
            "midfielders" => ["LM", "CM", "CM", "RM"],
            "forwards" => ["LW", "CF", "RW"]
        ]
    ],
    [
        "slug" => "4222",
        "name" => "4-2-2-2",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["CDM", "CDM", "CAM", "CAM"],
            "forwards" => ["ST", "ST"]
        ]
    ]
];
define("DEFAULT_FOOTBALL_FORMATION", $formations);
