<?php

$namesByNation = [
    "Argentina" => [
        ["firstname" => "Matías", "lastname" => "González"],
        ["firstname" => "Valentina", "lastname" => "Pérez"],
        ["firstname" => "Nicolás", "lastname" => "Fernández"],
        ["firstname" => "Camila", "lastname" => "Rodríguez"],
        ["firstname" => "Juan", "lastname" => "Martínez"],
        ["firstname" => "Santiago", "lastname" => "Romero"],
        ["firstname" => "Sofía", "lastname" => "Vega"],
        ["firstname" => "Facundo", "lastname" => "Morales"],
        ["firstname" => "Agustina", "lastname" => "Gutiérrez"],
        ["firstname" => "Tomás", "lastname" => "Díaz"],
    ],
    "France" => [
        ["firstname" => "Lucas", "lastname" => "Bernard"],
        ["firstname" => "Chloé", "lastname" => "Dubois"],
        ["firstname" => "Gabriel", "lastname" => "Moreau"],
        ["firstname" => "Emma", "lastname" => "Fournier"],
        ["firstname" => "Louis", "lastname" => "Girard"],
        ["firstname" => "Léa", "lastname" => "Lambert"],
        ["firstname" => "Hugo", "lastname" => "Martineau"],
        ["firstname" => "Alice", "lastname" => "Lemoine"],
        ["firstname" => "Arthur", "lastname" => "Rousseau"],
        ["firstname" => "Manon", "lastname" => "Chevalier"],
    ],
    "Brazil" => [
        ["firstname" => "Gabriel", "lastname" => "Silva"],
        ["firstname" => "Julia", "lastname" => "Oliveira"],
        ["firstname" => "Pedro", "lastname" => "Souza"],
        ["firstname" => "Ana", "lastname" => "Ferreira"],
        ["firstname" => "Rafael", "lastname" => "Almeida"],
        ["firstname" => "Isabela", "lastname" => "Castro"],
        ["firstname" => "Lucas", "lastname" => "Costa"],
        ["firstname" => "Mariana", "lastname" => "Ribeiro"],
        ["firstname" => "Felipe", "lastname" => "Gomes"],
        ["firstname" => "Carolina", "lastname" => "Santos"],
    ],
    "England" => [
        ["firstname" => "Oliver", "lastname" => "Taylor"],
        ["firstname" => "Amelia", "lastname" => "Brown"],
        ["firstname" => "Jack", "lastname" => "Wilson"],
        ["firstname" => "Isla", "lastname" => "Evans"],
        ["firstname" => "Henry", "lastname" => "Thomas"],
        ["firstname" => "Emily", "lastname" => "Johnson"],
        ["firstname" => "George", "lastname" => "Hall"],
        ["firstname" => "Mia", "lastname" => "Adams"],
        ["firstname" => "Freddie", "lastname" => "Walker"],
        ["firstname" => "Sophie", "lastname" => "Green"],
    ],
    "Belgium" => [
        ["firstname" => "Noah", "lastname" => "Peeters"],
        ["firstname" => "Liam", "lastname" => "Dupont"],
        ["firstname" => "Emma", "lastname" => "De Smet"],
        ["firstname" => "Olivia", "lastname" => "Vermeulen"],
        ["firstname" => "Lucas", "lastname" => "Jacobs"],
        ["firstname" => "Mila", "lastname" => "Willems"],
        ["firstname" => "Nathan", "lastname" => "Maes"],
        ["firstname" => "Charlotte", "lastname" => "De Wit"],
        ["firstname" => "Eli", "lastname" => "Janssen"],
        ["firstname" => "Ella", "lastname" => "Claes"],
    ],
    "Portugal" => [
        ["firstname" => "Francisco", "lastname" => "Alves"],
        ["firstname" => "Beatriz", "lastname" => "Pereira"],
        ["firstname" => "Tiago", "lastname" => "Monteiro"],
        ["firstname" => "Inês", "lastname" => "Carvalho"],
        ["firstname" => "João", "lastname" => "Martins"],
        ["firstname" => "Leonor", "lastname" => "Sousa"],
        ["firstname" => "Miguel", "lastname" => "Rodrigues"],
        ["firstname" => "Sofia", "lastname" => "Fernandes"],
        ["firstname" => "Diogo", "lastname" => "Costa"],
        ["firstname" => "Ana", "lastname" => "Gonçalves"],
    ],
    "Netherlands" => [
        ["firstname" => "Daan", "lastname" => "de Jong"],
        ["firstname" => "Lotte", "lastname" => "Jansen"],
        ["firstname" => "Ruben", "lastname" => "Bakker"],
        ["firstname" => "Sanne", "lastname" => "Visser"],
        ["firstname" => "Mees", "lastname" => "Smit"],
        ["firstname" => "Fleur", "lastname" => "de Vries"],
        ["firstname" => "Milan", "lastname" => "Hofman"],
        ["firstname" => "Tess", "lastname" => "Kramer"],
        ["firstname" => "Jasper", "lastname" => "de Boer"],
        ["firstname" => "Evi", "lastname" => "Peters"],
    ],
    "Spain" => [
        ["firstname" => "Alejandro", "lastname" => "Garcia"],
        ["firstname" => "Lucía", "lastname" => "Fernandez"],
        ["firstname" => "Carlos", "lastname" => "Lopez"],
        ["firstname" => "Maria", "lastname" => "Martinez"],
        ["firstname" => "Hugo", "lastname" => "Sanchez"],
        ["firstname" => "Sofia", "lastname" => "Gonzalez"],
        ["firstname" => "Daniel", "lastname" => "Perez"],
        ["firstname" => "Paula", "lastname" => "Diaz"],
        ["firstname" => "Javier", "lastname" => "Moreno"],
        ["firstname" => "Claudia", "lastname" => "Ruiz"],
    ],
    "Italy" => [
        ["firstname" => "Lorenzo", "lastname" => "Russo"],
        ["firstname" => "Giulia", "lastname" => "Ferrari"],
        ["firstname" => "Andrea", "lastname" => "Romano"],
        ["firstname" => "Martina", "lastname" => "Galli"],
        ["firstname" => "Marco", "lastname" => "Ricci"],
        ["firstname" => "Chiara", "lastname" => "Rossi"],
        ["firstname" => "Davide", "lastname" => "Greco"],
        ["firstname" => "Elena", "lastname" => "Conti"],
        ["firstname" => "Matteo", "lastname" => "Lombardi"],
        ["firstname" => "Aurora", "lastname" => "Barbieri"],
    ],
    "Croatia" => [
        ["firstname" => "Marko", "lastname" => "Horvat"],
        ["firstname" => "Ivana", "lastname" => "Novak"],
        ["firstname" => "Ivan", "lastname" => "Kovac"],
        ["firstname" => "Ana", "lastname" => "Maric"],
        ["firstname" => "Luka", "lastname" => "Jelic"],
        ["firstname" => "Maja", "lastname" => "Petrovic"],
        ["firstname" => "Filip", "lastname" => "Tomic"],
        ["firstname" => "Lucija", "lastname" => "Matic"],
        ["firstname" => "Nikola", "lastname" => "Boric"],
        ["firstname" => "Petra", "lastname" => "Radic"],
    ],
    "Germany" => [
        ["firstname" => "Maximilian", "lastname" => "Müller"],
        ["firstname" => "Sophia", "lastname" => "Schmidt"],
        ["firstname" => "Felix", "lastname" => "Schneider"],
        ["firstname" => "Hannah", "lastname" => "Fischer"],
        ["firstname" => "Lukas", "lastname" => "Weber"],
        ["firstname" => "Emma", "lastname" => "Becker"],
        ["firstname" => "Paul", "lastname" => "Hoffmann"],
        ["firstname" => "Lina", "lastname" => "Krause"],
        ["firstname" => "Jonas", "lastname" => "Wagner"],
        ["firstname" => "Marie", "lastname" => "Bauer"],
    ],
    "Morocco" => [
        ["firstname" => "Youssef", "lastname" => "El Amrani"],
        ["firstname" => "Fatima", "lastname" => "Bouazza"],
        ["firstname" => "Rachid", "lastname" => "El Idrissi"],
        ["firstname" => "Amina", "lastname" => "Bennani"],
        ["firstname" => "Karim", "lastname" => "Ouazzani"],
        ["firstname" => "Leila", "lastname" => "Tazi"],
        ["firstname" => "Omar", "lastname" => "Bouzid"],
        ["firstname" => "Nadia", "lastname" => "El Fakir"],
        ["firstname" => "Mohamed", "lastname" => "Belhaj"],
        ["firstname" => "Khadija", "lastname" => "Cherkaoui"],
    ],
    "Mexico" => [
        ["firstname" => "Juan", "lastname" => "Hernández"],
        ["firstname" => "Maria", "lastname" => "García"],
        ["firstname" => "Carlos", "lastname" => "Martínez"],
        ["firstname" => "Guadalupe", "lastname" => "López"],
        ["firstname" => "José", "lastname" => "González"],
        ["firstname" => "Ana", "lastname" => "Rodríguez"],
        ["firstname" => "Miguel", "lastname" => "Pérez"],
        ["firstname" => "Sofía", "lastname" => "Sánchez"],
        ["firstname" => "Diego", "lastname" => "Ramírez"],
        ["firstname" => "Daniela", "lastname" => "Torres"],
    ],
    "Uruguay" => [
        ["firstname" => "Martín", "lastname" => "Rodríguez"],
        ["firstname" => "Florencia", "lastname" => "Fernández"],
        ["firstname" => "Matías", "lastname" => "Pérez"],
        ["firstname" => "Camila", "lastname" => "García"],
        ["firstname" => "Juan", "lastname" => "González"],
        ["firstname" => "Sofía", "lastname" => "Martínez"],
        ["firstname" => "Facundo", "lastname" => "Lopez"],
        ["firstname" => "Agustina", "lastname" => "Sánchez"],
        ["firstname" => "Lucas", "lastname" => "Ramírez"],
        ["firstname" => "Valentina", "lastname" => "Alonso"],
    ],
    "Switzerland" => [
        ["firstname" => "Liam", "lastname" => "Meyer"],
        ["firstname" => "Emma", "lastname" => "Fischer"],
        ["firstname" => "Noah", "lastname" => "Weber"],
        ["firstname" => "Mia", "lastname" => "Müller"],
        ["firstname" => "Lea", "lastname" => "Zimmermann"],
        ["firstname" => "Luca", "lastname" => "Hofmann"],
        ["firstname" => "Elena", "lastname" => "Bauer"],
        ["firstname" => "Jonas", "lastname" => "Schmid"],
        ["firstname" => "Nina", "lastname" => "Berger"],
        ["firstname" => "Tim", "lastname" => "Keller"],
    ],
    "Colombia" => [
        ["firstname" => "Santiago", "lastname" => "Gómez"],
        ["firstname" => "Valeria", "lastname" => "Rodríguez"],
        ["firstname" => "Sebastián", "lastname" => "Martínez"],
        ["firstname" => "Camila", "lastname" => "López"],
        ["firstname" => "Juan", "lastname" => "Hernández"],
        ["firstname" => "Mariana", "lastname" => "Pérez"],
        ["firstname" => "Andrés", "lastname" => "Torres"],
        ["firstname" => "Isabella", "lastname" => "Ramírez"],
        ["firstname" => "Nicolás", "lastname" => "García"],
        ["firstname" => "Laura", "lastname" => "Castro"],
    ],
    "Senegal" => [
        ["firstname" => "Mamadou", "lastname" => "Diop"],
        ["firstname" => "Awa", "lastname" => "Ndiaye"],
        ["firstname" => "Ibrahima", "lastname" => "Faye"],
        ["firstname" => "Fatou", "lastname" => "Ba"],
        ["firstname" => "Cheikh", "lastname" => "Sy"],
        ["firstname" => "Mariama", "lastname" => "Fall"],
        ["firstname" => "Ousmane", "lastname" => "Thiam"],
        ["firstname" => "Astou", "lastname" => "Gaye"],
        ["firstname" => "Amadou", "lastname" => "Sow"],
        ["firstname" => "Khady", "lastname" => "Camara"],
    ],
    "USA" => [
        ["firstname" => "James", "lastname" => "Johnson"],
        ["firstname" => "Emma", "lastname" => "Brown"],
        ["firstname" => "Michael", "lastname" => "Williams"],
        ["firstname" => "Olivia", "lastname" => "Jones"],
        ["firstname" => "William", "lastname" => "Garcia"],
        ["firstname" => "Sophia", "lastname" => "Miller"],
        ["firstname" => "Ethan", "lastname" => "Davis"],
        ["firstname" => "Isabella", "lastname" => "Martinez"],
        ["firstname" => "Daniel", "lastname" => "Hernandez"],
        ["firstname" => "Ava", "lastname" => "Lopez"],
    ],
    "Japan" => [
        ["firstname" => "Hiroshi", "lastname" => "Tanaka"],
        ["firstname" => "Yumi", "lastname" => "Nakamura"],
        ["firstname" => "Kenta", "lastname" => "Yamamoto"],
        ["firstname" => "Aiko", "lastname" => "Kobayashi"],
        ["firstname" => "Satoshi", "lastname" => "Matsumoto"],
        ["firstname" => "Rina", "lastname" => "Takahashi"],
        ["firstname" => "Takeshi", "lastname" => "Sasaki"],
        ["firstname" => "Haruka", "lastname" => "Fujimoto"],
        ["firstname" => "Ryota", "lastname" => "Okada"],
        ["firstname" => "Kana", "lastname" => "Shimizu"],
    ],
    "Denmark" => [
        ["firstname" => "Lucas", "lastname" => "Hansen"],
        ["firstname" => "Freja", "lastname" => "Nielsen"],
        ["firstname" => "Oliver", "lastname" => "Jensen"],
        ["firstname" => "Emma", "lastname" => "Pedersen"],
        ["firstname" => "Oscar", "lastname" => "Andersen"],
        ["firstname" => "Sofia", "lastname" => "Christensen"],
        ["firstname" => "Noah", "lastname" => "Larsen"],
        ["firstname" => "Maja", "lastname" => "Rasmussen"],
        ["firstname" => "Victor", "lastname" => "Sorensen"],
        ["firstname" => "Clara", "lastname" => "Mikkelsen"],
    ],
    "Australia" => [
        ["firstname" => "Liam", "lastname" => "Smith"],
        ["firstname" => "Olivia", "lastname" => "Brown"],
        ["firstname" => "Ethan", "lastname" => "Wilson"],
        ["firstname" => "Charlotte", "lastname" => "Taylor"],
        ["firstname" => "Jack", "lastname" => "Johnson"],
        ["firstname" => "Ava", "lastname" => "Williams"],
        ["firstname" => "Harry", "lastname" => "Jones"],
        ["firstname" => "Mia", "lastname" => "Miller"],
        ["firstname" => "Benjamin", "lastname" => "Davis"],
        ["firstname" => "Emily", "lastname" => "Anderson"],
    ],
    "Serbia" => [
        ["firstname" => "Nikola", "lastname" => "Markovic"],
        ["firstname" => "Jovana", "lastname" => "Petrovic"],
        ["firstname" => "Milos", "lastname" => "Jovanovic"],
        ["firstname" => "Ana", "lastname" => "Nikolic"],
        ["firstname" => "Luka", "lastname" => "Stevanovic"],
        ["firstname" => "Ivana", "lastname" => "Milosevic"],
        ["firstname" => "Filip", "lastname" => "Djurdjevic"],
        ["firstname" => "Milica", "lastname" => "Kostic"],
        ["firstname" => "Marko", "lastname" => "Stojanovic"],
        ["firstname" => "Jelena", "lastname" => "Pavlovic"],
    ],
    "Poland" => [
        ["firstname" => "Jakub", "lastname" => "Nowak"],
        ["firstname" => "Anna", "lastname" => "Kowalska"],
        ["firstname" => "Piotr", "lastname" => "Wiśniewski"],
        ["firstname" => "Katarzyna", "lastname" => "Wójcik"],
        ["firstname" => "Marek", "lastname" => "Kaminski"],
        ["firstname" => "Zofia", "lastname" => "Lewandowska"],
        ["firstname" => "Tomasz", "lastname" => "Dąbrowski"],
        ["firstname" => "Magdalena", "lastname" => "Zielinska"],
        ["firstname" => "Wojciech", "lastname" => "Szymański"],
        ["firstname" => "Agnieszka", "lastname" => "Pawlak"],
    ],
    "Iran" => [
        ["firstname" => "Ali", "lastname" => "Hosseini"],
        ["firstname" => "Fatemeh", "lastname" => "Mohammadi"],
        ["firstname" => "Reza", "lastname" => "Karimi"],
        ["firstname" => "Zahra", "lastname" => "Ahmadi"],
        ["firstname" => "Mohammad", "lastname" => "Ebrahimi"],
        ["firstname" => "Sara", "lastname" => "Rasouli"],
        ["firstname" => "Hossein", "lastname" => "Sadeghi"],
        ["firstname" => "Maryam", "lastname" => "Kazemi"],
        ["firstname" => "Mehdi", "lastname" => "Gholami"],
        ["firstname" => "Amin", "lastname" => "Najafi"],
    ],
    "Korea Republic" => [
        ["firstname" => "Jae-ho", "lastname" => "Kim"],
        ["firstname" => "Min-seo", "lastname" => "Park"],
        ["firstname" => "Hyun-woo", "lastname" => "Lee"],
        ["firstname" => "Ji-hyun", "lastname" => "Choi"],
        ["firstname" => "Dong-hyun", "lastname" => "Jeong"],
        ["firstname" => "Seo-yeon", "lastname" => "Yoon"],
        ["firstname" => "Jin-ho", "lastname" => "Jang"],
        ["firstname" => "Ha-eun", "lastname" => "Kang"],
        ["firstname" => "Sung-min", "lastname" => "Oh"],
        ["firstname" => "Hye-jin", "lastname" => "Moon"],
    ],
    "Peru" => [
        ["firstname" => "Juan", "lastname" => "Castro"],
        ["firstname" => "Rosa", "lastname" => "Sánchez"],
        ["firstname" => "Carlos", "lastname" => "Flores"],
        ["firstname" => "María", "lastname" => "Guzmán"],
        ["firstname" => "José", "lastname" => "Ortega"],
        ["firstname" => "Ana", "lastname" => "Vargas"],
        ["firstname" => "Luis", "lastname" => "Mendoza"],
        ["firstname" => "Carmen", "lastname" => "Rojas"],
        ["firstname" => "Miguel", "lastname" => "Chávez"],
        ["firstname" => "Elena", "lastname" => "Salazar"],
    ],
    "Sweden" => [
        ["firstname" => "Erik", "lastname" => "Johansson"],
        ["firstname" => "Maja", "lastname" => "Andersson"],
        ["firstname" => "William", "lastname" => "Karlsson"],
        ["firstname" => "Alice", "lastname" => "Nilsson"],
        ["firstname" => "Lucas", "lastname" => "Svensson"],
        ["firstname" => "Elin", "lastname" => "Olsson"],
        ["firstname" => "Oscar", "lastname" => "Lindberg"],
        ["firstname" => "Ebba", "lastname" => "Persson"],
        ["firstname" => "Axel", "lastname" => "Pettersson"],
        ["firstname" => "Nora", "lastname" => "Berg"],
    ],
    "Ukraine" => [
        ["firstname" => "Dmytro", "lastname" => "Shevchenko"],
        ["firstname" => "Olena", "lastname" => "Bondarenko"],
        ["firstname" => "Oleksandr", "lastname" => "Tkachenko"],
        ["firstname" => "Yulia", "lastname" => "Koval"],
        ["firstname" => "Andriy", "lastname" => "Kravchenko"],
        ["firstname" => "Iryna", "lastname" => "Melnyk"],
        ["firstname" => "Viktor", "lastname" => "Klymenko"],
        ["firstname" => "Tetiana", "lastname" => "Hryhorenko"],
        ["firstname" => "Roman", "lastname" => "Horbach"],
        ["firstname" => "Kateryna", "lastname" => "Mazurenko"],
    ],
    "Chile" => [
        ["firstname" => "Francisco", "lastname" => "Muñoz"],
        ["firstname" => "Antonia", "lastname" => "Rojas"],
        ["firstname" => "Matías", "lastname" => "Gutiérrez"],
        ["firstname" => "Valentina", "lastname" => "Paredes"],
        ["firstname" => "Sebastián", "lastname" => "Vergara"],
        ["firstname" => "Camila", "lastname" => "Reyes"],
        ["firstname" => "Cristóbal", "lastname" => "Navarro"],
        ["firstname" => "Fernanda", "lastname" => "Vargas"],
        ["firstname" => "Diego", "lastname" => "Cortez"],
        ["firstname" => "Isabella", "lastname" => "Morales"],
    ],
    "Egypt" => [
        ["firstname" => "Ahmed", "lastname" => "Ali"],
        ["firstname" => "Fatma", "lastname" => "Hassan"],
        ["firstname" => "Mohamed", "lastname" => "Youssef"],
        ["firstname" => "Nour", "lastname" => "Mahmoud"],
        ["firstname" => "Omar", "lastname" => "Ismail"],
        ["firstname" => "Aya", "lastname" => "Sayed"],
        ["firstname" => "Khaled", "lastname" => "Farouk"],
        ["firstname" => "Mona", "lastname" => "Shahin"],
        ["firstname" => "Hussein", "lastname" => "Sobhy"],
        ["firstname" => "Salma", "lastname" => "Abdelrahman"],
    ],
    "Nigeria" => [
        ["firstname" => "Chinedu", "lastname" => "Okafor"],
        ["firstname" => "Amarachi", "lastname" => "Nwosu"],
        ["firstname" => "Tolu", "lastname" => "Adesina"],
        ["firstname" => "Emeka", "lastname" => "Iheanacho"],
        ["firstname" => "Funmi", "lastname" => "Ogunleye"],
        ["firstname" => "Kelechi", "lastname" => "Eze"],
        ["firstname" => "Ngozi", "lastname" => "Onyekuru"],
        ["firstname" => "Segun", "lastname" => "Bello"],
        ["firstname" => "Ifeoma", "lastname" => "Uche"],
        ["firstname" => "Tunde", "lastname" => "Oluwafemi"],
    ],
    "Tunisia" => [
        ["firstname" => "Mohamed", "lastname" => "Ben Ali"],
        ["firstname" => "Aymen", "lastname" => "Abdelkader"],
        ["firstname" => "Houssem", "lastname" => "Jemaa"],
        ["firstname" => "Fethi", "lastname" => "Belhaj"],
        ["firstname" => "Riadh", "lastname" => "Chikhaoui"],
        ["firstname" => "Yassine", "lastname" => "Khelil"],
        ["firstname" => "Amine", "lastname" => "Haddadi"],
        ["firstname" => "Anis", "lastname" => "Bouazizi"],
        ["firstname" => "Chamseddine", "lastname" => "Harbaoui"],
        ["firstname" => "Sabri", "lastname" => "Gharbi"],
    ],
    "Saudi Arabia" => [
        ["firstname" => "Fahad", "lastname" => "Al-Mutairi"],
        ["firstname" => "Salman", "lastname" => "Al-Harbi"],
        ["firstname" => "Nasser", "lastname" => "Al-Qahtani"],
        ["firstname" => "Majed", "lastname" => "Al-Otaibi"],
        ["firstname" => "Yasir", "lastname" => "Al-Dosari"],
        ["firstname" => "Abdulrahman", "lastname" => "Al-Ghamdi"],
        ["firstname" => "Omar", "lastname" => "Al-Suhaimi"],
        ["firstname" => "Bander", "lastname" => "Al-Shammari"],
        ["firstname" => "Ibrahim", "lastname" => "Al-Rashidi"],
        ["firstname" => "Khaled", "lastname" => "Al-Omari"],
    ],
    "Ecuador" => [
        ["firstname" => "Diego", "lastname" => "Castillo"],
        ["firstname" => "Carlos", "lastname" => "Aguirre"],
        ["firstname" => "Javier", "lastname" => "Molina"],
        ["firstname" => "Luis", "lastname" => "Espinoza"],
        ["firstname" => "Daniel", "lastname" => "Valencia"],
        ["firstname" => "Andrés", "lastname" => "Ayala"],
        ["firstname" => "Sofia", "lastname" => "Guerrero"],
        ["firstname" => "María", "lastname" => "Torres"],
        ["firstname" => "Juan", "lastname" => "Reyes"],
        ["firstname" => "Esteban", "lastname" => "Cabrera"],
    ],
    "Czech Republic" => [
        ["firstname" => "Petr", "lastname" => "Novák"],
        ["firstname" => "Jan", "lastname" => "Svoboda"],
        ["firstname" => "Lukáš", "lastname" => "Černý"],
        ["firstname" => "Tereza", "lastname" => "Procházková"],
        ["firstname" => "Kateřina", "lastname" => "Horáková"],
        ["firstname" => "Ondřej", "lastname" => "Krejčí"],
        ["firstname" => "Vojtěch", "lastname" => "Král"],
        ["firstname" => "Eliška", "lastname" => "Jelínková"],
        ["firstname" => "Tomáš", "lastname" => "Dvořák"],
        ["firstname" => "Adéla", "lastname" => "Zemanová"],
    ],
    "Austria" => [
        ["firstname" => "Lukas", "lastname" => "Bauer"],
        ["firstname" => "Florian", "lastname" => "Huber"],
        ["firstname" => "David", "lastname" => "Müller"],
        ["firstname" => "Anna", "lastname" => "Schmid"],
        ["firstname" => "Sophia", "lastname" => "Mayer"],
        ["firstname" => "Maximilian", "lastname" => "Weber"],
        ["firstname" => "Johanna", "lastname" => "Fischer"],
        ["firstname" => "Matthias", "lastname" => "Wagner"],
        ["firstname" => "Katharina", "lastname" => "Berger"],
        ["firstname" => "Stefan", "lastname" => "Gruber"],
    ],
];
define("DEFAULT_NAME_BY_NATIONALITY", $namesByNation);

const DEFAULT_FOOTBALL_TEAM = [
    [
        'uuid' => '1b6f4567-89a1-4c12-b2d3-7456123a7890',
        'slug' => 'phoenix-titans',
        'name' => 'Phoenix Titans',
    ],
    [
        'uuid' => '2c7e5678-90b2-5d23-c3e4-8567234b8901',
        'slug' => 'atlas-warriors',
        'name' => 'Atlas Warriors',
    ],
    [
        'uuid' => '3d8f6789-01c3-6e34-d4f5-9678345c9012',
        'slug' => 'crimson-falcons',
        'name' => 'Crimson Falcons',
    ],
    [
        'uuid' => '4e9g7890-12d4-7f45-e5g6-0789456d0123',
        'slug' => 'iron-wolves',
        'name' => 'Iron Wolves',
    ],
    [
        'uuid' => '5fah8901-23e5-8g56-f6h7-1890567e1234',
        'slug' => 'olympus-storm',
        'name' => 'Olympus Storm',
    ],
    [
        'uuid' => '6gbi9012-34f6-9h67-g7i8-2901678f2345',
        'slug' => 'eternal-dragons',
        'name' => 'Eternal Dragons',
    ],
    [
        'uuid' => '7hcj0123-45g7-0i78-h8j9-301278901345',
        'slug' => 'shadow-panthers',
        'name' => 'Shadow Panthers',
    ],
    [
        'uuid' => '8idk1234-56h8-1j89-i9k0-412389012456',
        'slug' => 'thundering-rhinos',
        'name' => 'Thundering Rhinos',
    ],
    [
        'uuid' => '9jel2345-67i9-2k90-j0l1-523490123567',
        'slug' => 'golden-stallions',
        'name' => 'Golden Stallions',
    ],
    [
        'uuid' => 'akfm3456-78j0-3l01-k1m2-634501234678',
        'slug' => 'silver-hawks',
        'name' => 'Silver Hawks',
    ],
    [
        'uuid' => 'bgln4567-89k1-4m12-l2n3-745612345789',
        'slug' => 'frost-giants',
        'name' => 'Frost Giants',
    ],
    [
        'uuid' => 'chmo5678-90l2-5n23-m3o4-856723456890',
        'slug' => 'midnight-torches',
        'name' => 'Midnight Torches',
    ],
    [
        'uuid' => 'dimp6789-01m3-6o34-n4p5-967834567901',
        'slug' => 'emerald-guardians',
        'name' => 'Emerald Guardians',
    ],
    [
        'uuid' => 'ejnq7890-12n4-7p45-o5q6-078945678012',
        'slug' => 'scarlet-blades',
        'name' => 'Scarlet Blades',
    ],
    [
        'uuid' => 'fkpr8901-23o5-8q56-p6r7-189056789123',
        'slug' => 'azure-knights',
        'name' => 'Azure Knights',
    ],
    [
        'uuid' => 'glqs9012-34p6-9r67-q7s8-290167890234',
        'slug' => 'ivory-sharks',
        'name' => 'Ivory Sharks',
    ],
    [
        'uuid' => 'hmrt0123-45q7-0s78-r8t9-301278901345',
        'slug' => 'blazing-comets',
        'name' => 'Blazing Comets',
    ],
    [
        'uuid' => 'inuv1234-56r8-1t89-s9u0-412389012456',
        'slug' => 'volcanic-eagles',
        'name' => 'Volcanic Eagles',
    ],
    [
        'uuid' => 'jowv2345-67s9-2u90-t0v1-523490123567',
        'slug' => 'steel-spartans',
        'name' => 'Steel Spartans',
    ],
    [
        'uuid' => 'kpxw3456-78t0-3v01-u1w2-634501234678',
        'slug' => 'radiant-monarchs',
        'name' => 'Radiant Monarchs',
    ],
    [
        'uuid' => 'lqwr4567-89z1-4w23-l2t4-745612345890',
        'slug' => 'celestial-tigers',
        'name' => 'Celestial Tigers',
    ],
    [
        'uuid' => 'mrst5678-90v2-5r34-n3s5-856723456901',
        'slug' => 'midnight-hawks',
        'name' => 'Midnight Hawks',
    ],
    [
        'uuid' => 'nuvq6789-01w3-6s45-m4t6-967834567902',
        'slug' => 'radiant-dragons',
        'name' => 'Radiant Dragons',
    ],
    [
        'uuid' => 'opfr7890-12x4-7z56-n5u7-078945678013',
        'slug' => 'thunder-spire',
        'name' => 'Thunder Spire',
    ],
    [
        'uuid' => 'pqgs8901-23z5-8w67-v6t8-189056789124',
        'slug' => 'gale-warriors',
        'name' => 'Gale Warriors',
    ],
    [
        'uuid' => 'qrtu9012-34u6-9x78-p7w9-290167890235',
        'slug' => 'storm-guardians',
        'name' => 'Storm Guardians',
    ],
    [
        'uuid' => 'rsuv2345-67w8-3y90-v7z1-523490123578',
        'slug' => 'lunar-knights',
        'name' => 'Lunar Knights',
    ],
    [
        'uuid' => 'stuw3456-78x9-4z01-w8y2-634501234679',
        'slug' => 'solar-ascendants',
        'name' => 'Solar Ascendants',
    ],
    [
        'uuid' => 'txyv4567-89y0-5w12-x9z3-745612345790',
        'slug' => 'oceanic-phantoms',
        'name' => 'Oceanic Phantoms',
    ],
    [
        'uuid' => 'uxyz5678-90z1-6y23-v0w4-856723456902',
        'slug' => 'crystal-vipers',
        'name' => 'Crystal Vipers',
    ],
    [
        'uuid' => 'vyza6789-01x2-7z34-w1y5-967834567903',
        'slug' => 'diamond-fury',
        'name' => 'Diamond Fury',
    ],
    [
        'uuid' => 'wzab7890-12y3-8z56-v2x7-078945678014',
        'slug' => 'wildfire-predators',
        'name' => 'Wildfire Predators',
    ],
    [
        'uuid' => 'xabc8901-23z4-9x67-y3z8-189056789125',
        'slug' => 'storm-wolves',
        'name' => 'Storm Wolves',
    ],
    [
        'uuid' => 'ydef9012-34z5-0w78-x6y9-290167890236',
        'slug' => 'frost-wardens',
        'name' => 'Frost Wardens',
    ],
    [
        'uuid' => 'zghj0123-45w6-2z89-v7y0-301278901346',
        'slug' => 'blizzard-sentinels',
        'name' => 'Blizzard Sentinels',
    ]
];

$formations = [
    [
        "slug" => "433",
        "name" => "4-3-3",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["LCM", "CM", "RCM"],
            "forwards" => ["LW", "CF", "RW"]
        ]
    ],
    [
        "slug" => "442",
        "name" => "4-4-2",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["LM", "CM", "CM", "RM"],
            "forwards" => ["ST", "ST"]
        ]
    ],
    [
        "slug" => "352",
        "name" => "3-5-2",
        "player_positions" => [
            "defenders" => ["CB", "CB", "CB"],
            "midfielders" => ["LM", "LCM", "CM", "RCM", "RM"],
            "forwards" => ["ST", "ST"]
        ]
    ],
    [
        "slug" => "4231",
        "name" => "4-2-3-1",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["CDM", "CDM", "CAM", "LW", "RW"],
            "forwards" => ["ST"]
        ]
    ],
    [
        "slug" => "4141",
        "name" => "4-1-4-1",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["CDM", "LM", "CM", "CM", "RM"],
            "forwards" => ["ST"]
        ]
    ],
    [
        "slug" => "541",
        "name" => "5-4-1",
        "player_positions" => [
            "defenders" => ["LWB", "CB", "CB", "CB", "RWB"],
            "midfielders" => ["LM", "CM", "CM", "RM"],
            "forwards" => ["ST"]
        ]
    ],
    [
        "slug" => "4312",
        "name" => "4-3-1-2",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["LCM", "CM", "RCM", "CAM"],
            "forwards" => ["ST", "ST"]
        ]
    ],
    [
        "slug" => "343",
        "name" => "3-4-3",
        "player_positions" => [
            "defenders" => ["CB", "CB", "CB"],
            "midfielders" => ["LM", "CM", "CM", "RM"],
            "forwards" => ["LW", "CF", "RW"]
        ]
    ],
    [
        "slug" => "4222",
        "name" => "4-2-2-2",
        "player_positions" => [
            "defenders" => ["LB", "CB", "CB", "RB"],
            "midfielders" => ["CDM", "CDM", "CAM", "CAM"],
            "forwards" => ["ST", "ST"]
        ]
    ]
];
define("DEFAULT_FOOTBALL_FORMATION", $formations);

$seasons = [
    'Legend' => 80,
    'The Best' => 72,
    'Superstar' => 67,
    'Rising Star' => 60,
    'Normal' => 0,
];

// Possible values for player attributes
$positions = ['GK', 'CM', 'CF', 'ST', 'RW', 'LW', 'CB', 'RB', 'LB', 'DM', 'AMC', 'LM', 'RM'];
// Define position groups
$positionGroups = [
    'Goalkeepers' => ['GK'],
    'Defenders' => ['CB', 'RB', 'LB'],
    'Midfielders' => ['CM', 'DM', 'AMC', 'LM', 'RM'],
    'Attackers' => ['CF', 'ST', 'RW', 'LW'],
];
$positionGroupsExtra = [
    'Goalkeepers' => ['GK'],
    'Defenders' => ['CB', 'LCB', 'RCB', 'RB', 'LB'],
    'Midfielders' => ['CM', 'RCM', 'LCM', 'DM', 'AMC', 'LM', 'RM'],
    'Attackers' => ['CF', 'ST', 'LF', 'RF', 'RW', 'LW'],
];
$seasonsRate = [
    'Legend' => 1.5,
    'The Best' => 1.3,
    'Superstar' => 1.2,
    'Rising Star' => 1.1,
    'Normal' => 1.0,
];
// Updated Popular Nations: Top 10 FIFA rankings for 2024
$popularNations = [
    "Argentina",
    "France",
    "Brazil",
    "England",
    "Belgium",
    "Portugal",
    "Netherlands",
    "Spain",
    "Italy",
    "Croatia"
];
// Updated Semi-Popular Nations: Ranked 11-30 FIFA rankings for 2024
$semiPopularNations = [
    "Germany",
    "Morocco",
    "Mexico",
    "Uruguay",
    "Switzerland",
    "Colombia",
    "Senegal",
    "USA",
    "Japan",
    "Denmark",
    "Australia",
    "Serbia",
    "Poland",
    "Iran",
    "Korea Republic",
    "Peru",
    "Sweden",
    "Ukraine",
    "Chile",
    "Egypt"
];

const DEFAULT_STORE_ITEMS = [
    [
        'id' => 1,
        'name' => 'Normal Player',
        'slug' => 'normal-player',
        'price' => 1000000,
        'description' => 'Get a new Normal Player with balanced stats.',
        'type' => 'player',
        'rarity' => 'normal',
        'attributes' => [
            'position' => 'any',
            'skill_level' => 50,
            'potential' => 60,
        ],
        'image' => 'images/normal-player.jpg',
    ],
    [
        'id' => 2,
        'name' => 'Rising Star Player',
        'slug' => 'rising-star-player',
        'price' => 3000000,
        'description' => 'Get a new Rising Star Player with high potential.',
        'type' => 'player',
        'rarity' => 'rare',
        'attributes' => [
            'position' => 'any',
            'skill_level' => 70,
            'potential' => 90,
        ],
        'image' => 'images/rising-star-player.jpg',
    ],
    [
        'id' => 3,
        'name' => 'Superstar Player',
        'slug' => 'superstar-player',
        'price' => 5000000,
        'description' => 'Get a Superstar Player with excellent stats.',
        'type' => 'player',
        'rarity' => 'epic',
        'attributes' => [
            'position' => 'forward',
            'skill_level' => 85,
            'potential' => 95,
        ],
        'image' => 'images/superstar-player.jpg',
    ],
    [
        'id' => 4,
        'name' => 'The Best Player',
        'slug' => 'the-best-player',
        'price' => 8000000,
        'description' => 'Get a top-tier player, one of the best in the world.',
        'type' => 'player',
        'rarity' => 'legendary',
        'attributes' => [
            'position' => 'midfielder',
            'skill_level' => 95,
            'potential' => 99,
        ],
        'image' => 'images/the-best-player.jpg',
    ],
    [
        'id' => 5,
        'name' => 'Legend Player',
        'slug' => 'legend-player',
        'price' => 12000000,
        'description' => 'Get a Legendary player with unbeatable stats.',
        'type' => 'player',
        'rarity' => 'legendary',
        'attributes' => [
            'position' => 'any',
            'skill_level' => 99,
            'potential' => 100,
        ],
        'image' => 'images/legend-player.jpg',
    ],
    [
        'id' => 6,
        'name' => 'Legendary Pack',
        'slug' => 'legendary-pack',
        'price' => 20000000,
        'description' => 'Unlock a Legendary player with rare attributes and skills.',
        'type' => 'pack',
        'rarity' => 'legendary',
        'items_included' => 1,
        'image' => 'images/legendary-pack.jpg',
    ],
    [
        'id' => 7,
        'name' => 'Premium Pack',
        'slug' => 'premium-pack',
        'price' => 10000000,
        'description' => 'Unlock a high-value player with a mix of Superstar, The Best, or Legend players.',
        'type' => 'pack',
        'rarity' => 'epic',
        'items_included' => 1,
        'image' => 'images/premium-pack.jpg',
    ],
    [
        'id' => 8,
        'name' => 'Superstar Pack',
        'slug' => 'superstar-pack',
        'price' => 7500000,
        'description' => 'Unlock a Superstar player with high stats.',
        'type' => 'pack',
        'rarity' => 'epic',
        'items_included' => 1,
        'image' => 'images/superstar-pack.jpg',
    ],
    [
        'id' => 9,
        'name' => 'Season Pass',
        'slug' => 'season-pass',
        'price' => 25000000,
        'description' => 'Get access to exclusive players and events for an entire season.',
        'type' => 'pass',
        'rarity' => 'special',
        'benefits' => [
            'exclusive_players' => true,
            'bonus_events' => true,
            'discounts' => 10, // percentage
        ],
        'image' => 'images/season-pass.jpg',
    ],
    [
        'id' => 10,
        'name' => 'Player Upgrade Token',
        'slug' => 'player-upgrade-token',
        'price' => 1500000,
        'description' => 'Upgrade a player’s skill level and stats to a higher tier.',
        'type' => 'utility',
        'rarity' => 'common',
        'effects' => [
            'skill_increase' => 5, // percentage
            'max_potential_increase' => 5, // percentage
        ],
        'image' => 'images/player-upgrade-token.jpg',
    ],
    [
        'name' => 'Young Talent Pack',
        'slug' => 'young-talent-pack',
        'price' => 2000000,
        'description' => 'Unlock a promising young player with high potential growth.',
    ],
    [
        'name' => 'Veteran Player Pack',
        'slug' => 'veteran-player-pack',
        'price' => 4000000,
        'description' => 'Get an experienced player to bring stability and leadership to your team.',
    ],
    [
        'name' => 'Mystery Pack',
        'slug' => 'mystery-pack',
        'price' => 5500000,
        'description' => 'Get a completely random player, ranging from Normal to Legend.',
    ],
    [
        'name' => 'Defensive Specialist Pack',
        'slug' => 'defensive-specialist-pack',
        'price' => 3500000,
        'description' => 'Unlock a top-tier defender or goalkeeper to strengthen your defense.',
    ],
    [
        'name' => 'Offensive Specialist Pack',
        'slug' => 'offensive-specialist-pack',
        'price' => 3500000,
        'description' => 'Unlock a forward or midfielder known for scoring or creating goals.',
    ],
    [
        'name' => 'Training Booster',
        'slug' => 'training-booster',
        'price' => 1000000,
        'description' => 'Boost the growth of a player’s stats by 10% during training sessions.',
    ],
    [
        'name' => 'Skill Upgrade Card',
        'slug' => 'skill-upgrade-card',
        'price' => 2000000,
        'description' => 'Upgrade a specific skill (e.g., passing, shooting) of a player by one level.',
    ],
    [
        'name' => 'Stamina Booster',
        'slug' => 'stamina-booster',
        'price' => 800000,
        'description' => 'Fully restore the stamina of a player for the next match.',
    ],
    [
        'name' => 'XP Multiplier (x2)',
        'slug' => 'xp-multiplier',
        'price' => 3000000,
        'description' => 'Double the experience points gained by your players for 5 matches.',
    ],
    [
        'name' => 'Iconic Player Pack',
        'slug' => 'iconic-player-pack',
        'price' => 15000000,
        'description' => 'Get a legendary player inspired by real-life football icons.',
    ],
    [
        'name' => 'Event Exclusive Player',
        'slug' => 'event-exclusive-player',
        'price' => 12000000,
        'description' => 'Obtain a rare player available only for a limited time.',
    ],
    [
        'name' => 'Custom Player Pack',
        'slug' => 'custom-player-pack',
        'price' => 20000000,
        'description' => 'Create a player with your desired stats and position.',
    ],
    [
        'name' => 'Tactical Blueprint',
        'slug' => 'tactical-blueprint',
        'price' => 1500000,
        'description' => 'Unlock a unique formation or tactic to improve team performance.',
    ],
    [
        'name' => 'Team Morale Booster',
        'slug' => 'team-morale-booster',
        'price' => 2000000,
        'description' => 'Increase your entire team’s morale for the next 3 matches.',
    ],
    [
        'name' => 'Team Performance Booster',
        'slug' => 'team-performance-booster',
        'price' => 2500000,
        'description' => 'Temporarily improve your team\'s overall performance by 5% for the next match.',
    ],
    [
        'name' => 'Custom Kit',
        'slug' => 'custom-kit',
        'price' => 1000000,
        'description' => 'Design a unique team kit to stand out on the pitch.',
    ],
    [
        'name' => 'Custom Stadium Pack',
        'slug' => 'custom-stadium-pack',
        'price' => 5000000,
        'description' => 'Unlock a custom stadium with enhanced visuals and crowd effects.',
    ],
    [
        'name' => 'Fan Banner',
        'slug' => 'fan-banner',
        'price' => 500000,
        'description' => 'Add banners and chants to your stadium to increase crowd support.',
    ],
    [
        'name' => 'Event Participation Ticket',
        'slug' => 'event-participation-ticket',
        'price' => 1000000,
        'description' => 'Join a special event to compete for exclusive rewards.',
    ],
    [
        'name' => 'Special Transfer Token',
        'slug' => 'special-transfer-token',
        'price' => 3000000,
        'description' => 'Get a rare player transfer from a special event.',
    ],

    // Added Items
    [
        'name' => 'Future Star Pack',
        'slug' => 'future-star-pack',
        'price' => 3000000,
        'description' => 'Unlock a young player with exceptional potential to dominate future seasons.',
    ],
    [
        'name' => 'Elite Midfielder Pack',
        'slug' => 'elite-midfielder-pack',
        'price' => 4500000,
        'description' => 'Add a world-class midfielder known for creativity and control.',
    ],
    [
        'name' => 'Golden Goalkeeper Pack',
        'slug' => 'golden-goalkeeper-pack',
        'price' => 3000000,
        'description' => 'Strengthen your team with a top-tier goalkeeper who guarantees clean sheets.',
    ],
    [
        'name' => 'Wildcard Pack',
        'slug' => 'wildcard-pack',
        'price' => 6000000,
        'description' => 'Get a player with a random skill boost, making them unpredictable on the pitch.',
    ],
    [
        'name' => 'Injury Recovery Pack',
        'slug' => 'injury-recovery-pack',
        'price' => 2000000,
        'description' => 'Heal all injured players in your squad instantly.',
    ],
    [
        'name' => 'Speed Booster',
        'slug' => 'speed-booster',
        'price' => 1200000,
        'description' => 'Enhance a player’s speed stats by 10% for 3 matches.',
    ],
    [
        'name' => 'Captain’s Boost',
        'slug' => 'captains-boost',
        'price' => 2500000,
        'description' => 'Temporarily improve your team captain’s stats to inspire the team.',
    ],
    [
        'name' => 'Matchday Booster Pack',
        'slug' => 'matchday-booster-pack',
        'price' => 1800000,
        'description' => 'Improve your entire team\'s stamina and performance for one crucial match.',
    ],
    [
        'name' => 'Rival Player Transfer',
        'slug' => 'rival-player-transfer',
        'price' => 18000000,
        'description' => 'Poach a star player from your biggest rival to weaken them and strengthen your squad.',
    ],
    [
        'name' => 'Golden Age Player Pack',
        'slug' => 'golden-age-player-pack',
        'price' => 13000000,
        'description' => 'Get a player inspired by the greatest footballers of the past.',
    ],
    [
        'name' => 'Set-Piece Master Tactic',
        'slug' => 'set-piece-master-tactic',
        'price' => 2000000,
        'description' => 'Unlock a specialized tactic to dominate free kicks and corners.',
    ],
    [
        'name' => 'Home Advantage Boost',
        'slug' => 'home-advantage-boost',
        'price' => 2500000,
        'description' => 'Increase your team\'s morale and fan support for home games.',
    ],
    [
        'name' => 'Advanced Scouting Report',
        'slug' => 'advanced-scouting-report',
        'price' => 1500000,
        'description' => 'Gain insights into your next opponent’s tactics and weaknesses.',
    ],
    [
        'name' => 'Retro Kit Pack',
        'slug' => 'retro-kit-pack',
        'price' => 1500000,
        'description' => 'Unlock classic kits inspired by your team’s history.',
    ],
    [
        'name' => 'Mascot Unlock',
        'slug' => 'mascot-unlock',
        'price' => 2000000,
        'description' => 'Add a team mascot to boost crowd morale and branding.',
    ],
    [
        'name' => 'Stadium Light Show',
        'slug' => 'stadium-light-show',
        'price' => 1000000,
        'description' => 'Enhance your stadium atmosphere with a custom light show for night matches.',
    ],
    [
        'name' => 'Tournament Entry Token',
        'slug' => 'tournament-entry-token',
        'price' => 2000000,
        'description' => 'Join a global tournament with massive rewards for top players.',
    ],
    [
        'name' => 'Exclusive Player Draft',
        'slug' => 'exclusive-player-draft',
        'price' => 5000000,
        'description' => 'Participate in a draft to choose from a pool of rare players.',
    ],
    [
        'name' => 'Legends Coaching Staff',
        'slug' => 'legends-coaching-staff',
        'price' => 10000000,
        'description' => 'Hire a legendary player as your coach to boost training and tactics.',
    ],
    [
        'name' => 'Youth Academy Expansion',
        'slug' => 'youth-academy-expansion',
        'price' => 7500000,
        'description' => 'Invest in your youth academy to discover top young talent.',
    ],
    [
        'name' => 'Global Scouting Network',
        'slug' => 'global-scouting-network',
        'price' => 5000000,
        'description' => 'Unlock scouts from around the world to find hidden gems.',
    ],
    [
        'name' => 'Extra Challenge Ticket',
        'slug' => 'extra-challenge-ticket',
        'price' => 500000,
        'description' => 'Play an additional challenge match beyond the daily limit.',
    ],
    [
        'name' => 'Challenge Stamina Restore',
        'slug' => 'challenge-stamina-restore',
        'price' => 200000,
        'description' => 'Restore stamina to retry a failed challenge immediately.',
    ],
    [
        'name' => 'Challenge Boost Pack',
        'slug' => 'challenge-boost-pack',
        'price' => 1000000,
        'description' => 'Temporarily increase your team\'s stats by 10% for the next challenge.',
    ],
    [
        'name' => 'Challenge Bonus Reward',
        'slug' => 'challenge-bonus-reward',
        'price' => 800000,
        'description' => 'Earn 50% more rewards (money, XP, etc.) from your next challenge match.',
    ],

    // League-Related Items
    [
        'name' => 'League Participation Token',
        'slug' => 'league-participation-token',
        'price' => 2000000,
        'description' => 'Unlock access to join the next season of the league.',
    ],
    [
        'name' => 'League Revival Pass',
        'slug' => 'league-revival-pass',
        'price' => 1500000,
        'description' => 'Revive your team in a league after being eliminated.',
    ],
    [
        'name' => 'League Prestige Pack',
        'slug' => 'league-prestige-pack',
        'price' => 5000000,
        'description' => 'Get exclusive league-themed rewards, such as special players or kits.',
    ],
    [
        'name' => 'League Match Boost',
        'slug' => 'league-match-boost',
        'price' => 3000000,
        'description' => 'Temporarily increase your team\'s stats by 15% for one league match.',
    ],

    // My Club-Related Items
    [
        'name' => 'Club Expansion Pack',
        'slug' => 'club-expansion-pack',
        'price' => 3000000,
        'description' => 'Increase your squad size to add more players to your roster.',
    ],
    [
        'name' => 'Club Training Facility Upgrade',
        'slug' => 'training-facility-upgrade',
        'price' => 5000000,
        'description' => 'Unlock better training facilities to speed up player growth by 10%.',
    ],
    [
        'name' => 'Club Reputation Booster',
        'slug' => 'club-reputation-booster',
        'price' => 4000000,
        'description' => 'Improve your club’s reputation to attract higher-quality players.',
    ],
    [
        'name' => 'Custom Club Branding Pack',
        'slug' => 'custom-club-branding-pack',
        'price' => 2000000,
        'description' => 'Customize your club’s logo, kit, and stadium to make it unique.',
    ],
    [
        'name' => 'Special Coach Contract',
        'slug' => 'special-coach-contract',
        'price' => 1500000,
        'description' => 'Hire a specialized coach to improve specific skills, such as defense or attack.',
    ],

    // My Money-Related Items
    [
        'name' => 'Money Multiplier (x2)',
        'slug' => 'money-multiplier',
        'price' => 1000000,
        'description' => 'Double the money earned from matches for the next 5 games.',
    ],
    [
        'name' => 'Sponsor Deal Pack',
        'slug' => 'sponsor-deal-pack',
        'price' => 3000000,
        'description' => 'Sign a sponsorship deal to earn extra money after every match.',
    ],
    [
        'name' => 'Daily Income Booster',
        'slug' => 'daily-income-booster',
        'price' => 2000000,
        'description' => 'Increase your daily income by 25% for the next week.',
    ],
    [
        'name' => 'Financial Recovery Pack',
        'slug' => 'financial-recovery-pack',
        'price' => 2500000,
        'description' => 'Instantly recover a portion of your lost money after a failed match.',
    ],
    [
        'name' => 'Investor Pack',
        'slug' => 'investor-pack',
        'price' => 10000000,
        'description' => 'Attract wealthy investors to increase your overall club funds by 10%.',
    ],

    // General Items
    [
        'name' => 'Legendary Challenge Player',
        'slug' => 'legendary-challenge-player',
        'price' => 15000000,
        'description' => 'Unlock a special player with elite stats for use in Challenge Matches.',
    ],
    [
        'name' => 'League Master Pack',
        'slug' => 'league-master-pack',
        'price' => 8000000,
        'description' => 'Gain an exclusive player, bonus money, and league boosts.',
    ],
    [
        'name' => 'Challenge Victory Trophy',
        'slug' => 'challenge-victory-trophy',
        'price' => 1200000,
        'description' => 'Display a trophy in your club\'s collection to commemorate winning challenges.',
    ],
    [
        'name' => 'Custom Match Ball',
        'slug' => 'custom-match-ball',
        'price' => 500000,
        'description' => 'Change the design of your match ball for a personal touch.',
    ],
];
