version: "3.8"

services:
  php:
    image: php:8.1-fpm
    container_name: php_app
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

networks:
  default:
    driver: bridge