<?php

function getPageData($slug, $role): array
{
    global $super_user_pack, $premium_user_pack, $standard_user_pack, $guest_user_pack;
    $routes = [
        '' => ['url' => DIR . '/views/dashboard.php', 'title' => 'Dashboard', 'role' => 3],
        'app' => ['url' => DIR . '/views/dashboard.php', 'title' => 'Dashboard', 'role' => 3],
        'my-profile' => ['url' => DIR . '/views/my-profile.php', 'title' => 'My Profile', 'role' => 3],
        'my-settings' => ['url' => DIR . '/views/my-setting.php', 'title' => 'My Setting', 'role' => 3],
        'my-notification' => ['url' => DIR . '/views/my-notification.php', 'title' => 'My Notification', 'role' => 3],
        'devices' => ['url' => DIR . '/views/devices.php', 'title' => 'Devices', 'role' => 0],
        'logout' => ['url' => DIR . '/views/logout.php', 'title' => 'Logout', 'role' => 3],
        'project' => ['url' => DIR . '/views/projects.php', 'title' => 'Project List', 'role' => 0],
        'project/new' => ['url' => DIR . '/views/project-adjust.php', 'title' => 'Create Project', 'role' => 0],
        'project/edit' => ['url' => DIR . '/views/project-adjust.php', 'title' => 'Edit Project', 'role' => 0],
        'project/detail' => ['url' => DIR . '/views/project-detail.php', 'title' => 'Project Detail', 'role' => 0],
        'project/report' => ['url' => DIR . '/views/report-working.php', 'title' => 'Project Report', 'role' => 0],
        'finance' => ['url' => DIR . '/views/finance.php', 'title' => 'Finance', 'role' => 3],
        'finance/budget' => ['url' => DIR . '/views/budget.php', 'title' => 'Budget', 'role' => 0],
        'finance/income' => ['url' => DIR . '/views/income.php', 'title' => 'Income', 'role' => 0],
        'finance/expenses' => ['url' => DIR . '/views/expenses.php', 'title' => 'Expenses', 'role' => 0],
        'version' => ['url' => DIR . '/views/version.php', 'title' => 'Version', 'role' => 0],
        'daily-checklist' => ['url' => DIR . '/views/daily-checklist.php', 'title' => 'Daily Checklist', 'role' => 0],
        'subscription' => ['url' => DIR . '/views/subscription.php', 'title' => 'Subscription', 'role' => 0],
        'subscription/new' => ['url' => DIR . '/views/subscription-adjust.php', 'title' => 'New Subscription', 'role' => 0],
        'subscription/edit' => ['url' => DIR . '/views/subscription-adjust.php', 'title' => 'Edit Subscription', 'role' => 0],
        'subscription/detail' => ['url' => DIR . '/views/subscription-detail.php', 'title' => 'Subscription Detail', 'role' => 0],
        'blog' => ['url' => DIR . '/views/blog.php', 'title' => 'Blog', 'role' => 0],
        'blog/new' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'New Blog', 'role' => 0],
        'blog/edit' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'Edit Blog', 'role' => 0],
        'blog/detail' => ['url' => DIR . '/views/blog-detail.php', 'title' => 'Blog Detail', 'role' => 0],
        'course' => ['url' => DIR . '/views/course.php', 'title' => 'Course', 'role' => 0],
        'course/new' => ['url' => DIR . '/views/course-adjust.php', 'title' => 'New Course', 'role' => 0],
        'course/edit' => ['url' => DIR . '/views/course-adjust.php', 'title' => 'Edit Course', 'role' => 0],
        'course/detail' => ['url' => DIR . '/views/course-detail.php', 'title' => 'Course Detail', 'role' => 0],
        'git' => ['url' => DIR . '/views/git.php', 'title' => 'Git', 'role' => 0],
        'git/new' => ['url' => DIR . '/views/git-adjust.php', 'title' => 'New Git', 'role' => 0],
        'git/edit' => ['url' => DIR . '/views/git-adjust.php', 'title' => 'Edit Git', 'role' => 0],
        'git/detail' => ['url' => DIR . '/views/git-detail.php', 'title' => 'Git Detail', 'role' => 0],
        'book' => ['url' => DIR . '/views/book.php', 'title' => 'Book', 'role' => 0],
        'book/new' => ['url' => DIR . '/views/book-adjust.php', 'title' => 'New Book', 'role' => 0],
        'book/edit' => ['url' => DIR . '/views/book-adjust.php', 'title' => 'Edit Book', 'role' => 0],
        'book/detail' => ['url' => DIR . '/views/book-detail.php', 'title' => 'Book Detail', 'role' => 0],
        'book/view' => ['url' => DIR . '/views/book-view.php', 'title' => 'Book Detail', 'role' => 0],
        'tip' => ['url' => DIR . '/views/tip.php', 'title' => 'Tip', 'role' => 0],
        'tip/new' => ['url' => DIR . '/views/tip-adjust.php', 'title' => 'New Tip', 'role' => 0],
        'tip/edit' => ['url' => DIR . '/views/tip-adjust.php', 'title' => 'Edit Tip', 'role' => 0],
        'tip/detail' => ['url' => DIR . '/views/tip-detail.php', 'title' => 'Tip Detail', 'role' => 0],
        'code' => ['url' => DIR . '/views/code.php', 'title' => 'Code', 'role' => 0],
        'code/new' => ['url' => DIR . '/views/code-adjust.php', 'title' => 'New Code', 'role' => 0],
        'code/edit' => ['url' => DIR . '/views/code-adjust.php', 'title' => 'Edit Code', 'role' => 0],
        'code/detail' => ['url' => DIR . '/views/code-detail.php', 'title' => 'Code Detail', 'role' => 0],
        'note' => ['url' => DIR . '/views/note.php', 'title' => 'Note', 'role' => 0],
        'note/new' => ['url' => DIR . '/views/note-adjust.php', 'title' => 'New Note', 'role' => 0],
        'note/edit' => ['url' => DIR . '/views/note-adjust.php', 'title' => 'Edit Note', 'role' => 0],
        'note/detail' => ['url' => DIR . '/views/note-detail.php', 'title' => 'Note Detail', 'role' => 0],
        'todo' => ['url' => DIR . '/views/todo.php', 'title' => 'Todo', 'role' => 3],
        'todo/new' => ['url' => DIR . '/views/todo-adjust.php', 'title' => 'New Todo', 'role' => 3],
        'todo/edit' => ['url' => DIR . '/views/todo-adjust.php', 'title' => 'Edit Todo', 'role' => 3],
        'todo/detail' => ['url' => DIR . '/views/todo-detail.php', 'title' => 'Todo Detail', 'role' => 3],
        'report-working' => ['url' => DIR . '/views/report-working.php', 'title' => 'Report Working', 'role' => 0],
        'report-working/new' => ['url' => DIR . '/views/report-working-adjust.php', 'title' => 'New Report Working', 'role' => 0],
        'report-working/edit' => ['url' => DIR . '/views/report-working-adjust.php', 'title' => 'Edit Report Working', 'role' => 0],
        'report-working/detail' => ['url' => DIR . '/views/report-working-detail.php', 'title' => 'Report Working Detail', 'role' => 0],
        'ai-chat' => ['url' => DIR . '/views/ai-chat.php', 'title' => 'AI Chat', 'role' => 0],
        'maintain-web' => ['url' => DIR . '/views/maintain-web.php', 'title' => 'Maintain Web', 'role' => 0],
        'lead' => ['url' => DIR . '/views/lead.php', 'title' => 'Lead', 'role' => 0],
        'website' => ['url' => DIR . '/views/website.php', 'title' => 'Website', 'role' => 0],
        'website/new' => ['url' => DIR . '/views/website-adjust.php', 'title' => 'New Website', 'role' => 3],
        'website/edit' => ['url' => DIR . '/views/website-adjust.php', 'title' => 'Edit Website', 'role' => 3],
        'website/detail' => ['url' => DIR . '/views/website-detail.php', 'title' => 'Website Detail', 'role' => 3],
        'football-manager' => ['url' => DIR . '/views/football-manager.php', 'title' => 'Football Manager', 'role' => 0],
        'football-manager/my-club' => ['url' => DIR . '/views/football-manager-club.php', 'title' => 'Football Manager - My Club', 'role' => 0],
        'football-manager/transfer' => ['url' => DIR . '/views/football-manager-transfer.php', 'title' => 'Football Manager - Transfer', 'role' => 0],
        'football-manager/transfer/buy-list' => ['url' => DIR . '/views/football-manager-transfer-buy-list.php', 'title' => 'Football Manager - Transfer Buy List', 'role' => 0],
        'football-manager/transfer/sell-list' => ['url' => DIR . '/views/football-manager-transfer-sell-list.php', 'title' => 'Football Manager - Transfer Sell List', 'role' => 0],
        'football-manager/transfer/favorite' => ['url' => DIR . '/views/football-manager-transfer-favorite.php', 'title' => 'Football Manager - Transfer Favorite', 'role' => 0],
        'football-manager/transfer/buy' => ['url' => DIR . '/views/football-manager-transfer-buy.php', 'title' => 'Football Manager - Transfer Buy Player', 'role' => 0],
        'football-manager/my-players' => ['url' => DIR . '/views/football-manager-players.php', 'title' => 'Football Manager - My Players', 'role' => 0],
        'football-manager/locker-room' => ['url' => DIR . '/views/football-manager-locker-room.php', 'title' => 'Football Manager - Locker Room', 'role' => 0],
        'football-manager/match' => ['url' => DIR . '/views/football-manager-match.php', 'title' => 'Football Manager - Match', 'role' => 0],
        'football-manager/match-result' => ['url' => DIR . '/views/football-manager-match-result.php', 'title' => 'Football Manager - Match Result', 'role' => 0],
        'football-manager/store' => ['url' => DIR . '/views/football-manager-store.php', 'title' => 'Football Manager - Store', 'role' => 0],
        'football-manager/store/inventory' => ['url' => DIR . '/views/football-manager-inventory.php', 'title' => 'Football Manager - Store Inventory', 'role' => 0],
        'football-manager/store/item' => ['url' => DIR . '/views/football-manager-store-item.php', 'title' => 'Football Manager - Store Item', 'role' => 0],
        'football-manager/player' => ['url' => DIR . '/views/football-manager-player-detail.php', 'title' => 'Football Manager - Player Detail', 'role' => 0],
        'wordpress' => ['url' => DIR . '/views/search-results.php', 'title' => 'Wordpress', 'role' => 0],
        'reactjs' => ['url' => DIR . '/views/search-results.php', 'title' => 'ReactJS', 'role' => 0],
        'salesforce' => ['url' => DIR . '/views/search-results.php', 'title' => 'Salesforce', 'role' => 0],
        'php' => ['url' => DIR . '/views/search-results.php', 'title' => 'PHP', 'role' => 0],
        'mysql' => ['url' => DIR . '/views/search-results.php', 'title' => 'MySql', 'role' => 0],
        'english' => ['url' => DIR . '/views/search-results.php', 'title' => 'English', 'role' => 0],
        'wallet' => ['url' => DIR . '/views/wallet.php', 'title' => 'My Wallet', 'role' => 0],
        'my-package' => ['url' => DIR . '/views/my-package.php', 'title' => 'Upgrade Account', 'role' => 3],
        'file-manager' => ['url' => DIR . '/views/file-manager.php', 'title' => 'File Manager', 'role' => 3],
        'file-manager/new' => ['url' => DIR . '/views/file-manager.php', 'title' => 'File Manager - New', 'role' => 3],
        'api-log' => ['url' => DIR . '/views/api-log.php', 'title' => 'API Log', 'role' => 0],
        'user-management' => ['url' => DIR . '/views/user-management.php', 'title' => 'User Management', 'role' => 0],
        'user-management/detail' => ['url' => DIR . '/views/user-management-detail.php', 'title' => 'User Management', 'role' => 0],
        'user-management/edit' => ['url' => DIR . '/views/user-management-detail.php', 'title' => 'User Management', 'role' => 0],
        'settings' => ['url' => DIR . '/views/settings.php', 'title' => 'Settings', 'role' => 0],
        'mail-log' => ['url' => DIR . '/views/mail-log.php', 'title' => 'Mail', 'role' => 0],
        'database' => ['url' => DIR . '/views/database.php', 'title' => 'Database', 'role' => 0],
        'search' => ['url' => DIR . '/views/search-results.php', 'title' => 'Database', 'role' => 3],
        'plan' => ['url' => DIR . '/views/plan.php', 'title' => 'Plan', 'role' => 0],
        'plan/new' => ['url' => DIR . '/views/plan-adjust.php', 'title' => 'Add Plan', 'role' => 0],
        'plan/edit' => ['url' => DIR . '/views/plan-adjust.php', 'title' => 'Edit Plan', 'role' => 0],
        'plan/detail' => ['url' => DIR . '/views/plan-detail.php', 'title' => 'Detail Plan', 'role' => 0],
        'calendar' => ['url' => DIR . '/views/calendar.php', 'title' => 'Calendar', 'role' => 3],
        'calendar/new' => ['url' => DIR . '/views/calendar-adjust.php', 'title' => 'Calendar', 'role' => 3],
        'calendar/edit' => ['url' => DIR . '/views/calendar-adjust.php', 'title' => 'Calendar', 'role' => 3],
        'system-error' => ['url' => DIR . '/views/system-error.php', 'title' => 'System Error', 'role' => 0],
        'system-notification' => ['url' => DIR . '/views/system-notification.php', 'title' => 'System Notification', 'role' => 0],
        'lucky-wheel' => ['url' => DIR . '/views/lucky-wheel.php', 'title' => 'Lucky Wheel', 'role' => 3],
        'number-guessing' => ['url' => DIR . '/views/number-guessing.php', 'title' => 'Number Guessing', 'role' => 3],
        'slot-machine' => ['url' => DIR . '/views/slot-machine.php', 'title' => 'Slot Machine', 'role' => 3],
        'flip-memory' => ['url' => DIR . '/views/flip-memory.php', 'title' => 'Flip Memory', 'role' => 3],
        'lottery-simulator' => ['url' => DIR . '/views/lottery-simulator.php', 'title' => 'Lottery Simulator', 'role' => 3],
        // redirectUser
        'dashboard' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect', 'role' => 3],
        'login' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect', 'role' => 3],
        'register' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect', 'role' => 3],
        'forgot-password' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect', 'role' => 3],
    ];

    $role_levels = [
        0 => $super_user_pack,
        1 => $premium_user_pack,
        2 => $standard_user_pack,
        3 => $guest_user_pack,
    ];

    if (isset($routes[$slug]) && file_exists($routes[$slug]['url'])) {
        if (isset($role) && in_array($role, $role_levels[$routes[$slug]['role']])) {
            return array_merge($routes[$slug], ['isAccessible' => true]);
        } else {
            return ['url' => DIR . '/views/403.php', 'title' => 'Access Denied'];
        }
    } else {
        return ['url' => DIR . '/views/404.php', 'title' => 'Page Not Found'];
    }
}
