<?php

function getPageData($slug, $role)
{
    $routes = [
        '' => ['url' => DIR . '/views/dashboard.php', 'title' => 'Dashboard', 'role' => 3],
        'app' => ['url' => DIR . '/views/dashboard.php', 'title' => 'Dashboard', 'role' => 3],
        'profile' => ['url' => DIR . '/views/profile.php', 'title' => 'Profile', 'role' => 0],
        'settings' => ['url' => DIR . '/views/settings.php', 'title' => 'Settings', 'role' => 0],
        'devices' => ['url' => DIR . '/views/devices.php', 'title' => 'Devices', 'role' => 0],
        'logout' => ['url' => DIR . '/views/logout.php', 'title' => 'Logout', 'role' => 0],
        'projects' => ['url' => DIR . '/views/project-overview.php', 'title' => 'Project Overview', 'role' => 0],
        'projects/overview' => ['url' => DIR . '/views/project-overview.php', 'title' => 'Project Overview', 'role' => 0],
        'projects/list' => ['url' => DIR . '/views/project-list.php', 'title' => 'Project List', 'role' => 0],
        'projects/create' => ['url' => DIR . '/views/project-modify.php', 'title' => 'Create Project', 'role' => 0],
        'projects/edit' => ['url' => DIR . '/views/project-modify.php', 'title' => 'Edit Project', 'role' => 0],
        'projects/detail' => ['url' => DIR . '/views/project-detail.php', 'title' => 'Project Detail', 'role' => 0],
        'projects/report' => ['url' => DIR . '/views/report-working.php', 'title' => 'Project Report', 'role' => 0],
        'finance' => ['url' => DIR . '/views/finance.php', 'title' => 'Finance', 'role' => 3],
        'finance/budget' => ['url' => DIR . '/views/budget.php', 'title' => 'Budget', 'role' => 0],
        'finance/income' => ['url' => DIR . '/views/income.php', 'title' => 'Income', 'role' => 0],
        'finance/expenses' => ['url' => DIR . '/views/expenses.php', 'title' => 'Expenses', 'role' => 0],
        'version' => ['url' => DIR . '/views/version.php', 'title' => 'Version', 'role' => 0],
        'daily-checklist' => ['url' => DIR . '/views/daily-checklist.php', 'title' => 'Daily Checklist', 'role' => 0],
        'bookmark' => ['url' => DIR . '/views/bookmark.php', 'title' => 'Bookmark', 'role' => 0],
        'subscription' => ['url' => DIR . '/views/subscription.php', 'title' => 'Subscription', 'role' => 0],
        'subscription/new' => ['url' => DIR . '/views/subscription-adjust.php', 'title' => 'New Subscription', 'role' => 0],
        'subscription/edit' => ['url' => DIR . '/views/subscription-adjust.php', 'title' => 'Edit Subscription', 'role' => 0],
        'subscription/detail' => ['url' => DIR . '/views/subscription-detail.php', 'title' => 'Subscription Detail', 'role' => 0],
        'blog' => ['url' => DIR . '/views/blog.php', 'title' => 'Blog', 'role' => 0],
        'blog/new' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'New Blog', 'role' => 0],
        'blog/edit' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'Edit Blog', 'role' => 0],
        'blog/detail' => ['url' => DIR . '/views/blog-detail.php', 'title' => 'Blog Detail', 'role' => 0],
        'course' => ['url' => DIR . '/views/course.php', 'title' => 'Course', 'role' => 0],
        'course/new' => ['url' => DIR . '/views/course-adjust.php', 'title' => 'New Course', 'role' => 0],
        'course/edit' => ['url' => DIR . '/views/course-adjust.php', 'title' => 'Edit Course', 'role' => 0],
        'course/detail' => ['url' => DIR . '/views/course-detail.php', 'title' => 'Course Detail', 'role' => 0],
        'git' => ['url' => DIR . '/views/git.php', 'title' => 'Git', 'role' => 0],
        'git/new' => ['url' => DIR . '/views/git-adjust.php', 'title' => 'New Git', 'role' => 0],
        'git/edit' => ['url' => DIR . '/views/git-adjust.php', 'title' => 'Edit Git', 'role' => 0],
        'git/detail' => ['url' => DIR . '/views/git-detail.php', 'title' => 'Git Detail', 'role' => 0],
        'book' => ['url' => DIR . '/views/book.php', 'title' => 'Book', 'role' => 0],
        'book/new' => ['url' => DIR . '/views/book-adjust.php', 'title' => 'New Book', 'role' => 0],
        'book/edit' => ['url' => DIR . '/views/book-adjust.php', 'title' => 'Edit Book', 'role' => 0],
        'book/detail' => ['url' => DIR . '/views/book-detail.php', 'title' => 'Book Detail', 'role' => 0],
        'tip' => ['url' => DIR . '/views/tip.php', 'title' => 'Tip', 'role' => 0],
        'tip/new' => ['url' => DIR . '/views/tip-adjust.php', 'title' => 'New Tip', 'role' => 0],
        'tip/edit' => ['url' => DIR . '/views/tip-adjust.php', 'title' => 'Edit Tip', 'role' => 0],
        'tip/detail' => ['url' => DIR . '/views/tip-detail.php', 'title' => 'Tip Detail', 'role' => 0],
        'code' => ['url' => DIR . '/views/code.php', 'title' => 'Code', 'role' => 0],
        'code/new' => ['url' => DIR . '/views/code-adjust.php', 'title' => 'New Code', 'role' => 0],
        'code/edit' => ['url' => DIR . '/views/code-adjust.php', 'title' => 'Edit Code', 'role' => 0],
        'code/detail' => ['url' => DIR . '/views/code-detail.php', 'title' => 'Code Detail', 'role' => 0],
        'note' => ['url' => DIR . '/views/note.php', 'title' => 'Note', 'role' => 0],
        'note/new' => ['url' => DIR . '/views/note-adjust.php', 'title' => 'New Note', 'role' => 0],
        'note/edit' => ['url' => DIR . '/views/note-adjust.php', 'title' => 'Edit Note', 'role' => 0],
        'note/detail' => ['url' => DIR . '/views/note-detail.php', 'title' => 'Note Detail', 'role' => 0],
        'todo' => ['url' => DIR . '/views/todo.php', 'title' => 'Todo', 'role' => 3],
        'todo/new' => ['url' => DIR . '/views/todo-adjust.php', 'title' => 'New Todo', 'role' => 3],
        'todo/edit' => ['url' => DIR . '/views/todo-adjust.php', 'title' => 'Edit Todo', 'role' => 3],
        'todo/detail' => ['url' => DIR . '/views/todo-detail.php', 'title' => 'Todo Detail', 'role' => 3],
        'report-working' => ['url' => DIR . '/views/report-working.php', 'title' => 'Report Working', 'role' => 0],
        'report-working/new' => ['url' => DIR . '/views/report-working-adjust.php', 'title' => 'New Report Working', 'role' => 0],
        'report-working/edit' => ['url' => DIR . '/views/report-working-adjust.php', 'title' => 'Edit Report Working', 'role' => 0],
        'report-working/detail' => ['url' => DIR . '/views/report-working-detail.php', 'title' => 'Report Working Detail', 'role' => 0],
        'ai-chat' => ['url' => DIR . '/views/ai-chat.php', 'title' => 'AI Chat', 'role' => 0],
        'maintain-web' => ['url' => DIR . '/views/maintain-web.php', 'title' => 'Maintain Web', 'role' => 0],
        'lead' => ['url' => DIR . '/views/lead.php', 'title' => 'Lead', 'role' => 0],
        'website' => ['url' => DIR . '/views/website.php', 'title' => 'Website', 'role' => 0],
        'football-manager' => ['url' => DIR . '/views/football-manager.php', 'title' => 'Football Manager', 'role' => 0],
        'football-manager/my-club' => ['url' => DIR . '/views/football-manager-club.php', 'title' => 'Football Manager - My Club', 'role' => 0],
        'football-manager/transfer' => ['url' => DIR . '/views/football-manager-transfer.php', 'title' => 'Football Manager - Transfer', 'role' => 0],
        'football-manager/transfer/buy-list' => ['url' => DIR . '/views/football-manager-transfer-buy-list.php', 'title' => 'Football Manager - Transfer Buy List', 'role' => 0],
        'football-manager/transfer/sell-list' => ['url' => DIR . '/views/football-manager-transfer-sell-list.php', 'title' => 'Football Manager - Transfer Sell List', 'role' => 0],
        'football-manager/transfer/favorite' => ['url' => DIR . '/views/football-manager-transfer-favorite.php', 'title' => 'Football Manager - Transfer Favorite', 'role' => 0],
        'football-manager/transfer/buy' => ['url' => DIR . '/views/football-manager-transfer-buy.php', 'title' => 'Football Manager - Transfer Buy Player', 'role' => 0],
        'football-manager/my-players' => ['url' => DIR . '/views/football-manager-players.php', 'title' => 'Football Manager - My Players', 'role' => 0],
        'football-manager/match' => ['url' => DIR . '/views/football-manager-match.php', 'title' => 'Football Manager - Match', 'role' => 0],
        'football-manager/store' => ['url' => DIR . '/views/football-manager-store.php', 'title' => 'Football Manager - Store', 'role' => 0],
        'football-manager/store/inventory' => ['url' => DIR . '/views/football-manager-inventory.php', 'title' => 'Football Manager - Store Inventory', 'role' => 0],
        'football-manager/store/item' => ['url' => DIR . '/views/football-manager-store-item.php', 'title' => 'Football Manager - Store Item', 'role' => 0],
        'wordpress' => ['url' => DIR . '/views/blog.php', 'title' => 'Wordpress', 'role' => 0],
        'wordpress/new' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'New Wordpress Blog', 'role' => 0],
        'wordpress/edit' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'Edit Wordpress Blog', 'role' => 0],
        'wordpress/detail' => ['url' => DIR . '/views/blog-detail.php', 'title' => 'Wordpress Blog Detail', 'role' => 0],
        'reactjs' => ['url' => DIR . '/views/blog.php', 'title' => 'ReactJS', 'role' => 0],
        'reactjs/new' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'New ReactJS Blog', 'role' => 0],
        'reactjs/edit' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'Edit ReactJS Blog', 'role' => 0],
        'reactjs/detail' => ['url' => DIR . '/views/blog-detail.php', 'title' => 'ReactJS Blog Detail', 'role' => 0],
        'salesforce' => ['url' => DIR . '/views/blog.php', 'title' => 'Salesforce', 'role' => 0],
        'salesforce/new' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'New Salesforce Blog', 'role' => 0],
        'salesforce/edit' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'Edit Salesforce Blog', 'role' => 0],
        'salesforce/detail' => ['url' => DIR . '/views/blog-detail.php', 'title' => 'Salesforce Blog Detail', 'role' => 0],
        'wallet' => ['url' => DIR . '/views/wallet.php', 'title' => 'My Wallet', 'role' => 0],
        'pricing' => ['url' => DIR . '/views/pricing.php', 'title' => 'Upgrade Account', 'role' => 3],
        // redirectUser
        'dashboard' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect', 'role' => 3],
        'login' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect', 'role' => 3],
        'register' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect', 'role' => 3],
        'forgot-password' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect', 'role' => 3],
    ];

    $role_levels = [
        0 => ['super_admin'],
        1 => ['super_admin', 'standard_user'],
        2 => ['super_admin', 'standard_user', 'premium_user'],
        3 => ['super_admin', 'standard_user', 'premium_user', 'guest'],
    ];

    if (isset($routes[$slug])) {
        if (isset($role) && in_array($role, $role_levels[$routes[$slug]['role']])) {
            return array_merge($routes[$slug], ['isAccessible' => true]);
        } else {
            return ['url' => DIR . '/views/403.php', 'title' => 'Access Denied'];
        }
    } else {
        return ['url' => DIR . '/views/404.php', 'title' => 'Page Not Found'];
    }
}
