<?php

function getPageData($slug)
{
    $routes = [
        '' => ['url' => DIR . '/views/dashboard.php', 'title' => 'Dashboard'],
        'app' => ['url' => DIR . '/views/dashboard.php', 'title' => 'Dashboard'],
        'profile' => ['url' => DIR . '/views/profile.php', 'title' => 'Profile'],
        'settings' => ['url' => DIR . '/views/settings.php', 'title' => 'Settings'],
        'devices' => ['url' => DIR . '/views/devices.php', 'title' => 'Devices'],
        'logout' => ['url' => DIR . '/views/logout.php', 'title' => 'Logout'],
        'projects' => ['url' => DIR . '/views/project-overview.php', 'title' => 'Project Overview'],
        'projects/overview' => ['url' => DIR . '/views/project-overview.php', 'title' => 'Project Overview'],
        'projects/list' => ['url' => DIR . '/views/project-list.php', 'title' => 'Project List'],
        'projects/create' => ['url' => DIR . '/views/project-modify.php', 'title' => 'Create Project'],
        'projects/edit' => ['url' => DIR . '/views/project-modify.php', 'title' => 'Edit Project'],
        'projects/detail' => ['url' => DIR . '/views/project-detail.php', 'title' => 'Project Detail'],
        'projects/report' => ['url' => DIR . '/views/report-working.php', 'title' => 'Project Report'],
        'finance' => ['url' => DIR . '/views/finance.php', 'title' => 'Finance'],
        'finance/budget' => ['url' => DIR . '/views/budget.php', 'title' => 'Budget'],
        'finance/income' => ['url' => DIR . '/views/income.php', 'title' => 'Income'],
        'finance/expenses' => ['url' => DIR . '/views/expenses.php', 'title' => 'Expenses'],
        'version' => ['url' => DIR . '/views/version.php', 'title' => 'Version'],
        'daily-checklist' => ['url' => DIR . '/views/daily-checklist.php', 'title' => 'Daily Checklist'],
        'bookmark' => ['url' => DIR . '/views/bookmark.php', 'title' => 'Bookmark'],
        'subscription' => ['url' => DIR . '/views/subscription.php', 'title' => 'Subscription'],
        'subscription/new' => ['url' => DIR . '/views/subscription-adjust.php', 'title' => 'New Subscription'],
        'subscription/edit' => ['url' => DIR . '/views/subscription-adjust.php', 'title' => 'Edit Subscription'],
        'subscription/detail' => ['url' => DIR . '/views/subscription-detail.php', 'title' => 'Subscription Detail'],
        'blog' => ['url' => DIR . '/views/blog.php', 'title' => 'Blog'],
        'blog/new' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'New Blog'],
        'blog/edit' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'Edit Blog'],
        'blog/detail' => ['url' => DIR . '/views/blog-detail.php', 'title' => 'Blog Detail'],
        'course' => ['url' => DIR . '/views/course.php', 'title' => 'Course'],
        'course/new' => ['url' => DIR . '/views/course-adjust.php', 'title' => 'New Course'],
        'course/edit' => ['url' => DIR . '/views/course-adjust.php', 'title' => 'Edit Course'],
        'course/detail' => ['url' => DIR . '/views/course-detail.php', 'title' => 'Course Detail'],
        'git' => ['url' => DIR . '/views/git.php', 'title' => 'Git'],
        'git/new' => ['url' => DIR . '/views/git-adjust.php', 'title' => 'New Git'],
        'git/edit' => ['url' => DIR . '/views/git-adjust.php', 'title' => 'Edit Git'],
        'git/detail' => ['url' => DIR . '/views/git-detail.php', 'title' => 'Git Detail'],
        'book' => ['url' => DIR . '/views/book.php', 'title' => 'Book'],
        'book/new' => ['url' => DIR . '/views/book-adjust.php', 'title' => 'New Book'],
        'book/edit' => ['url' => DIR . '/views/book-adjust.php', 'title' => 'Edit Book'],
        'book/detail' => ['url' => DIR . '/views/book-detail.php', 'title' => 'Book Detail'],
        'tip' => ['url' => DIR . '/views/tip.php', 'title' => 'Tip'],
        'tip/new' => ['url' => DIR . '/views/tip-adjust.php', 'title' => 'New Tip'],
        'tip/edit' => ['url' => DIR . '/views/tip-adjust.php', 'title' => 'Edit Tip'],
        'tip/detail' => ['url' => DIR . '/views/tip-detail.php', 'title' => 'Tip Detail'],
        'code' => ['url' => DIR . '/views/code.php', 'title' => 'Code'],
        'code/new' => ['url' => DIR . '/views/code-adjust.php', 'title' => 'New Code'],
        'code/edit' => ['url' => DIR . '/views/code-adjust.php', 'title' => 'Edit Code'],
        'code/detail' => ['url' => DIR . '/views/code-detail.php', 'title' => 'Code Detail'],
        'note' => ['url' => DIR . '/views/note.php', 'title' => 'Note'],
        'note/new' => ['url' => DIR . '/views/note-adjust.php', 'title' => 'New Note'],
        'note/edit' => ['url' => DIR . '/views/note-adjust.php', 'title' => 'Edit Note'],
        'note/detail' => ['url' => DIR . '/views/note-detail.php', 'title' => 'Note Detail'],
        'todo' => ['url' => DIR . '/views/todo.php', 'title' => 'Todo'],
        'todo/new' => ['url' => DIR . '/views/todo-adjust.php', 'title' => 'New Todo'],
        'todo/edit' => ['url' => DIR . '/views/todo-adjust.php', 'title' => 'Edit Todo'],
        'todo/detail' => ['url' => DIR . '/views/todo-detail.php', 'title' => 'Todo Detail'],
        'report-working' => ['url' => DIR . '/views/report-working.php', 'title' => 'Report Working'],
        'report-working/new' => ['url' => DIR . '/views/report-working-adjust.php', 'title' => 'New Report Working'],
        'report-working/edit' => ['url' => DIR . '/views/report-working-adjust.php', 'title' => 'Edit Report Working'],
        'report-working/detail' => ['url' => DIR . '/views/report-working-detail.php', 'title' => 'Report Working Detail'],
        'ai-chat' => ['url' => DIR . '/views/ai-chat.php', 'title' => 'AI Chat'],
        'maintain-web' => ['url' => DIR . '/views/maintain-web.php', 'title' => 'Maintain Web'],
        'lead' => ['url' => DIR . '/views/lead.php', 'title' => 'Lead'],
        'website' => ['url' => DIR . '/views/website.php', 'title' => 'Website'],
        'football-manager' => ['url' => DIR . '/views/football-manager.php', 'title' => 'Football Manager'],
        'football-manager/my-club' => ['url' => DIR . '/views/football-manager-club.php', 'title' => 'Football Manager - My Club'],
        'football-manager/transfer' => ['url' => DIR . '/views/football-manager-transfer.php', 'title' => 'Football Manager - Transfer'],
        'football-manager/transfer/buy-list' => ['url' => DIR . '/views/football-manager-transfer-buy-list.php', 'title' => 'Football Manager - Transfer Buy List'],
        'football-manager/transfer/sell-list' => ['url' => DIR . '/views/football-manager-transfer-sell-list.php', 'title' => 'Football Manager - Transfer Sell List'],
        'football-manager/transfer/favorite' => ['url' => DIR . '/views/football-manager-transfer-favorite.php', 'title' => 'Football Manager - Transfer Favorite'],
        'football-manager/transfer/buy' => ['url' => DIR . '/views/football-manager-transfer-buy.php', 'title' => 'Football Manager - Transfer Buy Player'],
        'football-manager/my-players' => ['url' => DIR . '/views/football-manager-players.php', 'title' => 'Football Manager - My Players'],
        'football-manager/match' => ['url' => DIR . '/views/football-manager-match.php', 'title' => 'Football Manager - Match'],
        'football-manager/store' => ['url' => DIR . '/views/football-manager-store.php', 'title' => 'Football Manager - Store'],
        'football-manager/store/inventory' => ['url' => DIR . '/views/football-manager-inventory.php', 'title' => 'Football Manager - Store Inventory'],
        'football-manager/store/item' => ['url' => DIR . '/views/football-manager-store-item.php', 'title' => 'Football Manager - Store Item'],
        'wordpress' => ['url' => DIR . '/views/blog.php', 'title' => 'Wordpress'],
        'wordpress/new' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'New Wordpress Blog'],
        'wordpress/edit' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'Edit Wordpress Blog'],
        'wordpress/detail' => ['url' => DIR . '/views/blog-detail.php', 'title' => 'Wordpress Blog Detail'],
        'reactjs' => ['url' => DIR . '/views/blog.php', 'title' => 'ReactJS'],
        'reactjs/new' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'New ReactJS Blog'],
        'reactjs/edit' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'Edit ReactJS Blog'],
        'reactjs/detail' => ['url' => DIR . '/views/blog-detail.php', 'title' => 'ReactJS Blog Detail'],
        'salesforce' => ['url' => DIR . '/views/blog.php', 'title' => 'Salesforce'],
        'salesforce/new' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'New Salesforce Blog'],
        'salesforce/edit' => ['url' => DIR . '/views/blog-adjust.php', 'title' => 'Edit Salesforce Blog'],
        'salesforce/detail' => ['url' => DIR . '/views/blog-detail.php', 'title' => 'Salesforce Blog Detail'],
        'wallet' => ['url' => DIR . '/views/wallet.php', 'title' => 'My Wallet'],
        // redirectUser
        'dashboard' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect'],
        'login' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect'],
        'register' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect'],
        'forgot-password' => ['url' => DIR . '/functions/redirectUser.php', 'title' => 'Redirect']
    ];

    // If the slug exists as a key in the routes array, return the corresponding page data
    return $routes[$slug] ?? ['url' => DIR . '/views/404.php', 'title' => 'Page Not Found'];
}
