<?php

define('DEFAULT_HOME_PATH', '');
define('DEFAULT_SITE_NAME', 'MultiPro');
define('DEFAULT_DATE_FORMAT', 'Y-m-d');
define('DEFAULT_TIME_FORMAT', 'H:i:s');
define('DEFAULT_DATETIME_FORMAT', 'Y-m-d H:i:s');

// Paths
define('BASE_PATH', 'http://localhost:8000');
define('APP_ROOT', dirname(__DIR__, 2));
define('PUBLIC_PATH', APP_ROOT . '/public/');
define('UPLOAD_PATH', APP_ROOT . '/public/uploads/');
define('VIEWS_PATH', APP_ROOT . '/app/views/');
define('LAYOUTS_PATH', APP_ROOT . '/app/views/layouts/');
define('ASSETS_PATH', BASE_PATH . '/public/assets/');
define('STORAGE_PATH', APP_ROOT . '/storage/');
define('LOGS_PATH', APP_ROOT . '/storage/logs/');
define('DIR_UPLOADS_PATH', APP_ROOT . '/storage/app/uploads/');
define('APP_UPLOADS_PATH', BASE_PATH . '/storage/app/uploads/');
define("VIEW_EXTENSION", ".php");
define("APP_VERSION", "1.0.0");

include "version.php";
include "bookmarks.php";
include "network.php";
include "dashboard.php";
include "football-manager.php";
include "user.php";

$timezones = [];
foreach (DateTimeZone::listIdentifiers() as $zone) {
    $timezones[$zone] = $zone;
}
define('TIMEZONES', $timezones);



$dailyChecklist = [
    ['id' => 1, 'name' => 'Wake up at your preferred time'],
    ['id' => 2, 'name' => 'Make your bed'],
    ['id' => 3, 'name' => 'Drink a glass of water'],
    ['id' => 4, 'name' => 'Exercise or stretch (15-30 mins)'],
    ['id' => 5, 'name' => 'Take a shower and get dressed'],
    ['id' => 6, 'name' => 'Eat a healthy breakfast'],
    ['id' => 7, 'name' => 'Review your daily plan or schedule'],
    ['id' => 8, 'name' => 'Check and reply to important emails or messages'],
    ['id' => 9, 'name' => 'Prioritize tasks for the day (set 3-5 main goals)'],
    ['id' => 10, 'name' => 'Focus on top-priority task for 1-2 hours'],
    ['id' => 11, 'name' => 'Take a short break (5-10 mins)'],
    ['id' => 12, 'name' => 'Attend meetings or calls'],
    ['id' => 13, 'name' => 'Review and update your task progress'],
    ['id' => 14, 'name' => 'Wash dishes after meals'],
    ['id' => 15, 'name' => 'Clean up a room or area (e.g., living room or kitchen)'],
    ['id' => 16, 'name' => 'Do laundry (if needed)'],
    ['id' => 17, 'name' => 'Organize clutter or tidy up workspaces'],
    ['id' => 18, 'name' => 'Meditate for 5-10 minutes'],
    ['id' => 19, 'name' => 'Read or learn something new for 30 minutes'],
    ['id' => 20, 'name' => 'Practice a hobby or skill (e.g., drawing, writing, coding)'],
    ['id' => 21, 'name' => 'Take breaks to relax and reset throughout the day'],
    ['id' => 22, 'name' => 'Plan the next day’s tasks or goals'],
    ['id' => 23, 'name' => 'Spend time with family or friends'],
    ['id' => 24, 'name' => 'Prepare dinner or enjoy a healthy meal'],
    ['id' => 25, 'name' => 'Unwind (read, watch a show, etc.)'],
    ['id' => 26, 'name' => 'Reflect on the day (what went well, what to improve)'],
    ['id' => 27, 'name' => 'Get ready for bed (brush teeth, wash face)'],
    ['id' => 28, 'name' => 'Sleep at a consistent time (get 7-8 hours of rest)'],
    ['id' => 29, 'name' => 'Drink 8 glasses of water'],
    ['id' => 30, 'name' => 'Eat 3 servings of vegetables'],
    ['id' => 31, 'name' => 'Walk 10,000 steps or exercise for 30 minutes'],
    ['id' => 32, 'name' => 'Take vitamins or medications'],
    ['id' => 33, 'name' => 'Review project deadlines'],
    ['id' => 34, 'name' => 'Focus on a deep work session (2-3 hours)'],
    ['id' => 35, 'name' => 'Attend any scheduled meetings'],
    ['id' => 36, 'name' => 'Follow up with clients or colleagues'],
    ['id' => 37, 'name' => 'Review course material for 1-2 hours'],
    ['id' => 38, 'name' => 'Practice exercises or take notes'],
    ['id' => 39, 'name' => 'Prepare for upcoming tests or exams'],
    ['id' => 40, 'name' => 'Review previous study sessions'],
    ['id' => 41, 'name' => 'Track your spending for the day'],
];
define("DEFAULT_DAILY_CHECKLISTS", $dailyChecklist);


const DEFAULT_BLOG_CATEGORIES = [
    'develop' => 'Develop',
    'wordpress' => 'Wordpress',
    'reactjs' => 'ReactJS',
    'salesforce' => 'Salesforce',
    'php' => 'PHP',
    'mysql' => 'MySql',
    'english' => 'English',
    'other' => 'Other',
];

$nations = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini (fmr. Swaziland)",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "England",
    "USA",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];
define("DEFAULT_NATIONALITY", $nations);

$player_cards = [
    'legend',
    'normal',
    'young',
    'demand'
];
define('DEFAULT_PLAYER_CARD', $player_cards);


$event_types = [
    "primary" => "Primary",
    "success" => "Success",
    "danger" => "Danger",
    "info" => "Info",
    "dark" => "Dark",
    "warning" => "Warning"
];
