<?php

use App\Controllers\AIController;
use App\Controllers\DatabaseController;
use App\Controllers\FileManagerController;
use App\Controllers\Football\FootballClubController;
use App\Controllers\Football\FootballPlayerController;
use App\Controllers\Football\FootballUserController;
use App\Controllers\FootballController;
use App\Controllers\PdfReaderController;
use App\Core\Router;
use App\Controllers\LandingController;
use App\Controllers\AuthController;
use App\Controllers\DashboardController;
use App\Controllers\TodoController;
use App\Controllers\NoteController;
use App\Controllers\HabitController;
use App\Controllers\IncomeController;
use App\Controllers\ExpenseController;
use App\Controllers\JournalController;
use App\Controllers\SubscriptionController;
use App\Controllers\PlanController;
use App\Controllers\CalendarController;
use App\Controllers\WorkoutController;
use App\Controllers\ProjectController;
use App\Controllers\TaskController;
use App\Controllers\ClientController;
use App\Controllers\EstimationController;
use App\Controllers\Football\FootballItemController;
use App\Controllers\Football\FootballLeagueController;
use App\Controllers\Football\FootballMatchController;
use App\Controllers\Football\FootballNewsController;
use App\Controllers\Football\FootballOnlineUserController;
use App\Controllers\Football\FootballScoutingController;
use App\Controllers\Football\FootballStadiumController;
use App\Controllers\Football\FootballStaffController;
use App\Controllers\Football\FootballTrainingController;
use App\Controllers\Football\FootballYouthAcademyController;
use App\Controllers\ResumeController;
use App\Controllers\ReportController;
use App\Controllers\MaintainWebController;
use App\Controllers\SeoChecklistController;
use App\Controllers\WebDevChecklistController;
use App\Controllers\WebSecureChecklistController;
use App\Controllers\LeadController;
use App\Controllers\WebsiteController;
use App\Controllers\SettingController;
use App\Controllers\NotificationsController;
use App\Controllers\PackageController;
use App\Controllers\ProfileController;
use App\Controllers\WebTemplateController;

$router = new Router();

$router->get('/', [LandingController::class, 'index']);
$router->get('/login', [AuthController::class, 'renderLogin']);
$router->post('/login', [AuthController::class, 'login']);
$router->get('/register', [AuthController::class, 'renderRegister']);
$router->get('/logout', [AuthController::class, 'logout'], 'auth');

// Dashboard routes
$router->get('/app', [DashboardController::class, 'index', 'auth']);
$router->get('/app/todo', [TodoController::class, 'index']);
$router->get('/app/note', [NoteController::class, 'index']);
$router->get('/app/habit', [HabitController::class, 'index']);
$router->get('/app/income', [IncomeController::class, 'index']);
$router->get('/app/expense', [ExpenseController::class, 'index']);
$router->get('/app/journal', [JournalController::class, 'index']);
$router->get('/app/subscription', [SubscriptionController::class, 'index']);
$router->get('/app/plan', [PlanController::class, 'index']);
$router->get('/app/calendar', [CalendarController::class, 'index']);
$router->get('/app/workout', [WorkoutController::class, 'index']);
$router->get('/app/project', [ProjectController::class, 'index']);
$router->get('/app/task', [TaskController::class, 'index']);
$router->get('/app/client', [ClientController::class, 'index']);
$router->get('/app/estimation', [EstimationController::class, 'index']);
$router->get('/app/resume', [ResumeController::class, 'index']);
$router->get('/app/report', [ReportController::class, 'index']);
$router->get('/app/maintain-web', [MaintainWebController::class, 'index']);
$router->get('/app/seo-checklist', [SeoChecklistController::class, 'index']);
$router->get('/app/web-dev-checklist', [WebDevChecklistController::class, 'index']);
$router->get('/app/web-secure-checklist', [WebSecureChecklistController::class, 'index']);
$router->get('/app/lead', [LeadController::class, 'index']);
$router->get('/app/website', [WebsiteController::class, 'index']);
$router->get('/app/ai-tools', [AIController::class, 'tools']);
$router->get('/app/ai-prompt', [AIController::class, 'prompt']);
$router->get('/app/settings', [SettingController::class, 'index']);
$router->get('/app/notifications', [NotificationsController::class, 'index']);
$router->get('/app/package', [PackageController::class, 'index']);
$router->get('/app/profile', [ProfileController::class, 'index']);
$router->get('/app/pdf-reader', [PdfReaderController::class, 'index']);
$router->get('/app/file-manager', [FileManagerController::class, 'index']);
$router->get('/app/database', [DatabaseController::class, 'index']);
$router->get('/app/football-player', [FootballController::class, 'index']);
$router->get('/app/web-template', [WebTemplateController::class, 'index']);
$router->get('/app/web-template/detail', [WebTemplateController::class, 'detail']);

// API
$router->get('/api/football/market/list', [FootballPlayerController::class, 'index']);
$router->get('/api/football/club/players', [FootballPlayerController::class, 'getClubPlayers']);
$router->get('/api/football/team', [FootballPlayerController::class, 'getTeamInfo']);
$router->post('/api/football/item/player-new', [FootballPlayerController::class, 'generatePlayer']);
$router->get('/api/football/user', [FootballUserController::class, 'index']);
$router->get('/api/football/club', [FootballClubController::class, 'index']);
$router->get('/api/football/stadium', [FootballStadiumController::class, 'index']);
$router->get('/api/football/league/standing', [FootballLeagueController::class, 'standing']);
$router->get('/api/football/league/schedule', [FootballLeagueController::class, 'schedule']);
$router->get('/api/football/news', [FootballNewsController::class, 'index']);
$router->get('/api/football/online/users', [FootballOnlineUserController::class, 'index']);
$router->get('/api/football/online/leaderboards', [FootballOnlineUserController::class, 'leaderboard']);
$router->get('/api/football/online/history', [FootballOnlineUserController::class, 'history']);
$router->get('/api/football/staff/available', [FootballStaffController::class, 'available']);
$router->get('/api/football/staff/own', [FootballStaffController::class, 'own']);
$router->get('/api/football/scouting/assignments', [FootballScoutingController::class, 'assignments']);
$router->get('/api/football/scouting/incoming', [FootballScoutingController::class, 'incoming']);
$router->get('/api/football/scouting/outgoing', [FootballScoutingController::class, 'outgoing']);
$router->get('/api/football/youth-academy/own', [FootballYouthAcademyController::class, 'own']);
$router->get('/api/football/youth-academy/assignments', [FootballYouthAcademyController::class, 'assignments']);
$router->get('/api/football/youth-academy/facilities', [FootballYouthAcademyController::class, 'facilities']);
$router->get('/api/football/training/team', [FootballTrainingController::class, 'team']);
$router->get('/api/football/training/player', [FootballTrainingController::class, 'player']);
$router->get('/api/football/item/shop', [FootballItemController::class, 'shop']);
$router->get('/api/football/item/inventory', [FootballItemController::class, 'inventory']);
$router->get('/api/football/match/upcoming', [FootballMatchController::class, 'upcoming']);



return $router;
